### ISSUE TITLE
Does the local-path storageclass support AllowVolumeExpansion or dynamic resize/expansion the PVC? 

### ISSUE THREAD

**Issue by walk1ng** [rancher/local-path-provisioner#107]
If it support, could you please figure out how to do this?
I have a try to edit the local-path storageclass to add the below:
```yaml
allowVolumeExpansion: true
```
then I edit the PVC created from local-path storageclass to update the `spec.resources.requests.storage` to larger size, edit successfully but the capacity size is not change/expansion, any mistake here? 

Thanks a lot!

**Comment by frederiko** [comment]
I may be wrong, but this is ignored when using in PV.

**Comment by yasker** [comment]
Local Path Provisioner doesn't take PVC size into consideration, since it's backed by a directory on the node. So there is no quota/enforcement for the volume size.

**Comment by timvol** [comment]
@yasker Sorry for my ignorance, but does it mean when I request 1G my database or so can also have 5G?

**Comment by cstruck** [comment]
> @yasker Sorry for my ignorance, but does it mean when I request 1G my database or so can also have 5G?

it means that it can have up to the full storage capacity of the node the volume is created on

**Comment by sjmiller609** [comment]
We are using it for testing a workload that uses storage, inside kubernetes-in-docker. For us, quota enforcement is irrelevant, but we just want to check our management of stateful sets.

I think it also does not update the status field. If you manually change allow volume expansion to true, then if you change the PVC request to a larger number the status field will remain at the original number.

**Comment by xixiangzouyibian** [comment]
> Local Path Provisioner doesn't take PVC size into consideration, since it's backed by a directory on the node. So there is no quota/enforcement for the volume size.

Thanks for your explanation.
