### ISSUE TITLE
Custom teardown script doesn't work

### ISSUE THREAD

**Issue by rxbn** [rancher/local-path-provisioner#108]
I've tried to set a custom teardown script using Helm values:

```yaml
teardown: |-
  #!/bin/sh
  path=$1
  archived_path="$(dirname ${path})/archived-$(basename ${path})"
  mv ${path} ${archived_path}
```

Although the config map gets updated to the new teardown script, when I delete a pvc local-path-provisioner still deletes the pv folder instead of running the script.

Any help would be appreciated :-)

**Comment by nicktming** [comment]
@rxbn 
hi, i tried to reproduce your problem, but it works well.

my configMap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt/local-path-provisioner"]
                },
                {
                        "node":"yasker-lp-dev1",
                        "paths":["/opt/local-path-provisioner", "/data1"]
                },
                {
                        "node":"yasker-lp-dev3",
                        "paths":[]
                }
                ]
        }
  setup: |-
        #!/bin/sh
        path=$1
        mkdir -m 0777 -p ${path}
  teardown: |-
        #!/bin/sh
        path=$1
        archived_path="$(dirname ${path})/archived-$(basename ${path})"
        mv ${path} ${archived_path}
```
and did as follows:
# ADD
```
# kubectl apply -f examples/pvc.yaml 
persistentvolumeclaim/local-path-pvc created
# kubectl get pvc
NAME             STATUS    VOLUME             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
local-path-pvc   Pending                                                local-path     7s
# kubectl apply -f examples/pod.yaml 
# kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
local-path-pvc   Bound    pvc-bfe590db-02f7-4986-8455-789c769a2a20   2Gi        RWO            local-path     61s
# ls -la /opt/local-path-provisioner/
drwxr-xr-x  3 root root  77 7月  28 11:08 .
drwxr-xr-x. 9 root root 133 6月  16 16:20 ..
drwxrwxrwx  2 root root   6 7月  28 11:08 pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc
```
# DELETE
```
# kubectl delete -f examples/pod.yaml 
pod "volume-test" deleted
# kubectl delete -f examples/pvc.yaml 
persistentvolumeclaim "local-path-pvc" deleted
# ls -la /opt/local-path-provisioner/
drwxr-xr-x  3 root root  86 7月  28 11:10 .
drwxr-xr-x. 9 root root 133 6月  16 16:20 ..
drwxrwxrwx  2 root root   6 7月  28 11:08 archived-pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc
```

so the pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc was renamed as archived-pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc , that was what the teardown script did.

**Comment by nicktming** [comment]
@rxbn 
hi, i tried to reproduce your problem, but it works well.

my configMap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt/local-path-provisioner"]
                },
                {
                        "node":"yasker-lp-dev1",
                        "paths":["/opt/local-path-provisioner", "/data1"]
                },
                {
                        "node":"yasker-lp-dev3",
                        "paths":[]
                }
                ]
        }
  setup: |-
        #!/bin/sh
        path=$1
        mkdir -m 0777 -p ${path}
  teardown: |-
        #!/bin/sh
        path=$1
        archived_path="$(dirname ${path})/archived-$(basename ${path})"
        mv ${path} ${archived_path}
```
and did as follows:
# ADD
```
# kubectl apply -f examples/pvc.yaml 
persistentvolumeclaim/local-path-pvc created
# kubectl get pvc
NAME             STATUS    VOLUME             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
local-path-pvc   Pending                                                local-path     7s
# kubectl apply -f examples/pod.yaml 
# kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
local-path-pvc   Bound    pvc-bfe590db-02f7-4986-8455-789c769a2a20   2Gi        RWO            local-path     61s
# ls -la /opt/local-path-provisioner/
drwxr-xr-x  3 root root  77 7月  28 11:08 .
drwxr-xr-x. 9 root root 133 6月  16 16:20 ..
drwxrwxrwx  2 root root   6 7月  28 11:08 pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc
```
# DELETE
```
# kubectl delete -f examples/pod.yaml 
pod "volume-test" deleted
# kubectl delete -f examples/pvc.yaml 
persistentvolumeclaim "local-path-pvc" deleted
# ls -la /opt/local-path-provisioner/
drwxr-xr-x  3 root root  86 7月  28 11:10 .
drwxr-xr-x. 9 root root 133 6月  16 16:20 ..
drwxrwxrwx  2 root root   6 7月  28 11:08 archived-pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc
```

so the pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc was renamed as archived-pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc , that was what the teardown script did.

**Comment by nicktming** [comment]
@rxbn 
hi, i tried to reproduce your problem, but it works well.

my configMap:
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: local-path-storage
data:
  config.json: |-
        {
                "nodePathMap":[
                {
                        "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                        "paths":["/opt/local-path-provisioner"]
                },
                {
                        "node":"yasker-lp-dev1",
                        "paths":["/opt/local-path-provisioner", "/data1"]
                },
                {
                        "node":"yasker-lp-dev3",
                        "paths":[]
                }
                ]
        }
  setup: |-
        #!/bin/sh
        path=$1
        mkdir -m 0777 -p ${path}
  teardown: |-
        #!/bin/sh
        path=$1
        archived_path="$(dirname ${path})/archived-$(basename ${path})"
        mv ${path} ${archived_path}
```
and did as follows:
# ADD
```
# kubectl apply -f examples/pvc.yaml 
persistentvolumeclaim/local-path-pvc created
# kubectl get pvc
NAME             STATUS    VOLUME             CAPACITY   ACCESS MODES   STORAGECLASS   AGE
local-path-pvc   Pending                                                local-path     7s
# kubectl apply -f examples/pod.yaml 
# kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
local-path-pvc   Bound    pvc-bfe590db-02f7-4986-8455-789c769a2a20   2Gi        RWO            local-path     61s
# ls -la /opt/local-path-provisioner/
drwxr-xr-x  3 root root  77 7月  28 11:08 .
drwxr-xr-x. 9 root root 133 6月  16 16:20 ..
drwxrwxrwx  2 root root   6 7月  28 11:08 pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc
```
# DELETE
```
# kubectl delete -f examples/pod.yaml 
pod "volume-test" deleted
# kubectl delete -f examples/pvc.yaml 
persistentvolumeclaim "local-path-pvc" deleted
# ls -la /opt/local-path-provisioner/
drwxr-xr-x  3 root root  86 7月  28 11:10 .
drwxr-xr-x. 9 root root 133 6月  16 16:20 ..
drwxrwxrwx  2 root root   6 7月  28 11:08 archived-pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc
```

so the pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc was renamed as archived-pvc-bfe590db-02f7-4986-8455-789c769a2a20_default_local-path-pvc , that was what the teardown script did.

**Comment by rxbn** [comment]
Thanks for the tests! Do I have to recreate the storage classes in order to make the custom teardown script working? I just redeployed the helm chart.

**Comment by nicktming** [comment]
there is no need to recreate the sc, but the new image of local-path-provisioner is needed.

**Comment by rxbn** [comment]
I already have the latest version `v.0.0.14`

**Comment by nicktming** [comment]
maybe you can build the latest image by yourself.

**Comment by rxbn** [comment]
no difference...

**Comment by yasker** [comment]
@rxbn I think the master should work but I am planning cut a new release this week to include the customized setup/teardown script.

**Comment by rxbn** [comment]
@yasker That would be great, it'd be great if I could archive the folders instead of deleting it entirely. Maybe that would make a good built-in feature as well?

**Comment by SamDecrock** [comment]
Hi, I also have the same issue.
The folder just disappears instead of running the teardown script.
When can you release a new version or how do I build the master?

**Comment by yasker** [comment]
@SamDecrock @rxbn @nicktming Which Kubernetes distro you're using? I am troubleshooting this issue and found it doesn't work with Rancher RKE. But it might work with K3S.

**Comment by rxbn** [comment]
> @SamDecrock @rxbn @nicktming Which Kubernetes distro you're using? I am troubleshooting this issue and found it doesn't work with Rancher RKE. But it might work with K3S.

I'm using K3s.

**Comment by SamDecrock** [comment]
I'm using Kubernetes itself installed on a single node, version 1.16.12

**Comment by yasker** [comment]
@rxbn @SamDecrock can you retry using the latest master?

**Comment by rxbn** [comment]
Unfortunately, it doesn't work :( I'm using the following image: rancher/local-path-provisioner:v0.0.14 on K3s v1.18.6+k3s1

**Comment by SamDecrock** [comment]
With the latest master it works!

@rxbn you need to clone the repo, run `make` and then use the generated image.

**Comment by rxbn** [comment]
@SamDecrock Cool! Hmm, that's good to know. But this currently goes against by deploy workflow so I'll wait until a new release gets made.

**Comment by yasker** [comment]
@SamDecrock Thanks for the confirmation. I will cut a release now.

**Comment by rxbn** [comment]
@SamDecrock Did you use my teardown script?

**Comment by yasker** [comment]
v0.0.15 has been released. Give it a try.

**Comment by rxbn** [comment]
Hmm.. now I'm getting a strange error when creating a pvc:
```
time="2020-08-10T21:40:13Z" level=info msg="create the helper pod create-pvc-0b24cc08-d9c7-4db3-9674-9c2208f04fd2 into local-path-provisioner" 
I0810 21:40:13.924867       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"local-path-pvc", UID:"0b24cc08-d9c7-4db3-9674-9c2208f04fd2", APIVersion:"v1", ResourceVersion:"8066186", FieldPath:""}): type: 'Normal' reason: 'Provisioning' External provisioner is provisioning volume for claim "default/local-path-pvc"
W0810 21:42:14.637111       1 controller.go:893] Retrying syncing claim "0b24cc08-d9c7-4db3-9674-9c2208f04fd2" because failures 0 < threshold 15
E0810 21:42:14.637449       1 controller.go:913] error syncing claim "0b24cc08-d9c7-4db3-9674-9c2208f04fd2": failed to provision volume with StorageClass "nvme": failed to create volume pvc-0b24cc08-d9c7-4db3-9674-9c2208f04fd2: create process timeout after 120 seconds
I0810 21:42:14.640609       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"local-path-pvc", UID:"0b24cc08-d9c7-4db3-9674-9c2208f04fd2", APIVersion:"v1", ResourceVersion:"8066186", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "nvme": failed to create volume pvc-0b24cc08-d9c7-4db3-9674-9c2208f04fd2: create process timeout after 120 seconds
```

**Comment by yasker** [comment]
@rxbn sounds like the provisioner failed to wait for the helper pod to finish. Can you check if anything wrong with the helper pod? e.g. the `setup` script.

**Comment by rxbn** [comment]
@yasker A describe on the pod says:
```
Warning  FailedMount  7s (x5 over 15s)  kubelet, k3s  MountVolume.SetUp failed for volume "script" : configmap "local-path-config" not found
```

**Comment by yasker** [comment]
I don't think it can be automatically detected, so I think we should allow customization of the config name [here](https://github.com/rancher/local-path-provisioner/blob/master/provisioner.go#L371) cc @nicktming 

@rxbn In the meantime, can you create the config map `local-path-config` to workaround the issue?

**Comment by rxbn** [comment]
@yasker The config map was created by the Helm chart. It did work before version 0.0.15.

**Comment by SamDecrock** [comment]
> @SamDecrock Did you use my teardown script?

Yes. It’s an exact copy-paste of yours

**Comment by yasker** [comment]
> @yasker The configmap was created by the Helm chart. It did work before version 0.0.15.

Yes, it because the configmap name wasn't directly referenced by the provisioner. It was changed when introducing the setup/teardown script.

So since it's created by Helm, it's better if we can figure out a way to get the name of config map directly - or we might need to give up the automatic reload of the config map.

**Comment by nicktming** [comment]
> @SamDecrock @rxbn @nicktming Which Kubernetes distro you're using? I am troubleshooting this issue and found it doesn't work with Rancher RKE. But it might work with K3S.
> 
> The reason seems to be the replacement of hostPath with local volume.

@yasker i am using kubernetes v1.15.5

**Comment by nicktming** [comment]
> I don't think it can be automatically detected, so I think we should allow customization of the config name [here](https://github.com/rancher/local-path-provisioner/blob/master/provisioner.go#L371) cc @nicktming
> 
> @rxbn In the meantime, can you create the config map `local-path-config` to workaround the issue?

yes, i will follow this issue and make it a flag to customize for users.

**Comment by rxbn** [comment]
@nicktming @yasker Thanks for your effort! Since I currently cannot use local-path-provsioner (I have two separate instances running for multiple storage classes), I would appreciate a quick fix.

**Comment by yasker** [comment]
@rxbn I would recommend to revert back to use v0.0.14 in in the meantime for your case.

**Comment by yasker** [comment]
Local Path Provisioner v0.0.16 has been released. Can you check again if the issue has been fixed?

**Comment by rxbn** [comment]
@yasker Unfortunately, it did not work out of the box. I had to change the deployment spec to use the configMap name flag. I've created a pull request. #117

Can you merge this pr? I've tested it.

**Comment by rxbn** [comment]
With `v0.0.17` it works perfectly! I guess this issue can be closed now 👍
