### ISSUE TITLE
Will local-path-provisioner separate pvc replicas across the cluster

### ISSUE THREAD

**Issue by sadekunle** [rancher/local-path-provisioner#111]
I'm deploying a statefulset workload with 3 replicas. I see that the local-path-provisioner deploys all pvc replicas to one node. Is there a way to separate the pvc for each replica to a different node?

**Comment by yasker** [comment]
The scheduling of the storage is not controlled by the local path provisioner. It will `waitForFirstConsumer` (a.k.a. pod creation/scheduling). So if you use anti-affinity for the pods for the first time creation, the volumes should follow the pod's scheduling to the different nodes.

After first time, the PV would bound to a certain node and cannot be moved after.

**Comment by sadekunle** [comment]
Would I need to create a pvc for each replica? Trying to deploy the 3 replicas and after the first replica is deployed I get the following error.

Warning  FailedScheduling  <unknown>  default-scheduler  0/4 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't satisfy existing pods anti-affinity rules, 3 node(s) had volume node affinity conflict.

**Comment by yasker** [comment]
If there is only one PVC, it will only able to be on one node, since the data is stored in one node's hard drive.

**Comment by ThinCats** [comment]
`Statefulset` and `volumeClaimTemplates` may fit your needs

see [https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/)

**Comment by Donatas-L** [comment]
@yasker How with deployment which has multiple pods (replicas) would be possible to setup storage which is local for each pod? 

For example, we have 3 nodes with enough resources to schedule our pods and we want to schedule 3 pods on each node. Thus we would have PV on each node associated with each pod. 

From you comment: 

> If there is only one PVC, it will only able to be on one node, since the data is stored in one node's hard drive.

I would assume that's impossible if you only have one PVC. But is there any workaround to achieve this result?

**Comment by dfoxg** [comment]
I pointed my local-path-provisioner-Path to an glusterfs-mount, so all of my files are available on all k8s-nodes. How can I configure the local-path-provider that the error `had volume node affinity conflict` does not appear?
