### ISSUE TITLE
Add arm64v8 image

### ISSUE THREAD

**Issue by vchrisb** [rancher/local-path-provisioner#12]
adding arm64v8 support would be great!

**Comment by giminni** [comment]
I installed successfully k3s on arm64 with weave Net overlay network on a RockPro64 cluster 
and made my own private local-path-provisioner arm64v8 instance using Alpine Linux instead of Ubuntu:18.04. Alpine Linux image size is 84Mi, testing was successful. 

```
$ uname -a
Linux <server> 4.4.167-1161-rockchip-ayufan-g6f1664023387 #1 SMP Fri Mar 22 23:03:38 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
<user>@<server>:<home-dir>$ k get all -n local-path-storage
NAME                                          READY   STATUS    RESTARTS   AGE
pod/local-path-provisioner-6868fbd6c6-nvjk5   1/1     Running   0          22m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/local-path-provisioner   1/1     1            1           22m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/local-path-provisioner-6868fbd6c6   1         1         1       22m
```
IMHO alpine linux reduce the footprint even further.

Should I make a PR using Alpine Linux?

**Comment by yasker** [comment]
@giminni Sure, that would be great!

Though I don't have a setup to test arm64, so I would be unable to fix if there is anything wrong with Arm. But I am OK on accepting a PR for arm64 as long as there is no impact on running with x86.

**Comment by anitgandhi** [comment]
@giminni we switched to Alpine in #13 , I think adding arm64/multi-arch support can build off that potentially?

**Comment by optimuspaul** [comment]
have any arm images been pushed anywhere?

**Comment by yasker** [comment]
Can anyone try @km4rcus 's image? The build has been merged to master as well.

**Comment by vchrisb** [comment]
@yasker can you initiate a build to docker hub?

**Comment by optimuspaul** [comment]
I haven't tried that specific build but I did build it for arm myself and it is working

**Comment by yasker** [comment]
v0.0.8 released and the image pushed. Let me know if it works.

**Comment by vchrisb** [comment]
@yasker I don't see any multi-arch image tags on docker hub and also no manifest to support multi-arch

**Comment by yasker** [comment]
@vchrisb sorry, not familiar with multi arch build. Let me check what should I do for an arm image.

**Comment by tamsky** [comment]
https://github.com/prometheus/prometheus/pull/5031 may have a useful example of "what to do" re: multi-arch

**Comment by tamsky** [comment]
@yasker , please take a look at 
https://github.com/rancher/dapper/blob/master/scripts/build
for a rancher-approved dapper-style example.

**Comment by ljani** [comment]
`arm` image seems to be missing as well, this is what I got on a raspberry pi:

```
kubectl logs -n local-path-storage pod/local-path-provisioner-69fc9568b9-vg4m2                             standard_init_linux.go:211: exec user process caused "exec format error"
```

**Comment by tamsky** [comment]
@yasker please take a look at #24 , thanks!

**Comment by yasker** [comment]
@tamsky Thanks for the help! I will check it.

**Comment by nielsole** [comment]
Can we /reopen this ticket as it is still waiting for #24 to be merged?

**Comment by yasker** [comment]
Multiarch supported in v0.0.11 release.

https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.11
