### ISSUE TITLE
Need to use rancher-mirrored busybox for helper image

### ISSUE THREAD

**Issue by brandond** [rancher/local-path-provisioner#120]
The [default helper image](https://github.com/rancher/local-path-provisioner/blob/master/main.go#L33) pulls busybox from the docker library. This should be changed to pull from the Rancher image mirror (docker.io/rancher/busybox), in line with other project images.

**Comment by dweomer** [comment]
Hmm, it looks like there is proper support across architectures to me: https://hub.docker.com/_/busybox?tab=tags

![Screenshot from 2020-08-20 04-58-26](https://user-images.githubusercontent.com/1033444/90767335-e2bef980-e2a1-11ea-84dc-fec5439dc044.png)

Why is this necessary?

**Comment by brandond** [comment]
yeah @dweomer the upstream image is fine. Our image mirroring script just doesn't support multiarch at the moment: https://github.com/rancher/image-mirror#mirroring-types
