### ISSUE TITLE
enable helper pod configurable to meet more users requirements

### ISSUE THREAD

**Issue by nicktming** [rancher/local-path-provisioner#128]
inspired by #125 needs to support block device and #126 need to support quota for size limitation which should add some volumes to helper pods, So i make the whole helper pod configurable which is more flexible for users to meet their needs.

In local-path-provisioner, it parse the users' helper pod and add its necessary information to this helper pod such as command and some parameters.

**Comment by innobead** [comment]
This was resolved by #127. Closing.
