### ISSUE TITLE
Why Kubernetes v1.12+.

### ISSUE THREAD

**Issue by linclaus** [rancher/local-path-provisioner#129]
Why required  kubernetes v1.12+ when deploying a local-path-provisioner?

**Comment by linclaus** [comment]
I want to deploy local-path-provisioner on kubernetes v1.9

**Comment by yasker** [comment]
The feature used by local path provisioner is only introduced to Kubernetes as a beta feature in v1.10. For v1.9, you can try to enable the `Local Volume` feature gate and to see if it works. We still cannot officially support the Kubernetes version before v1.12 though.
