### ISSUE TITLE
Unmounted storage protection

### ISSUE THREAD

**Issue by kvaps** [rancher/local-path-provisioner#137]
Hi the created volumes are having `type: DirectoryOrCreate` property.
But it might be unsafe in case if data storage is unmounted for some reason, because application can be started with the empty directory created in different place.

I'm sure that using `type: Directory` will solve this problem

https://github.com/rancher/local-path-provisioner/blob/b44b2c3b5d18772aa306d3fb1210b202c353ef09/provisioner.go#L205

**Comment by yasker** [comment]
Sorry @kvaps I need to revert this change now. Somehow it doesn't work with my RKE cluster. I always get the error when trying to start the pod:
```
MountVolume.SetUp failed for volume "pvc-xxxx" : hostPath type check failed: /opt/local-path-provisioner/pvc-xxxxx is not a directory
```

**Comment by kvaps** [comment]
But is it directory? :)

**Comment by yasker** [comment]
Yes it is…

**Comment by kvaps** [comment]
Weird, what kubelet vedsion do you have?

**Comment by yasker** [comment]
I am using Rancher Kubernetes Engine (RKE), which is a containerized kubelet.

**Comment by lllamnyp** [comment]
I'm out of context, but most likely if you're using RKE, you will need to specify somewhere in your cluster.yml something along the lines of
```
kubelet:
  extra_binds:
  - /opt/local-path-provisioner
```
refer to the RKE docs to get everything right.

**Comment by kvaps** [comment]
Okay I prepared a new PR https://github.com/rancher/local-path-provisioner/pull/224
