### ISSUE TITLE
local-path-provisioner does not work in an airgapped setup

### ISSUE THREAD

**Issue by sowmyav27** [rancher/local-path-provisioner#139]
Testing on rancher `v2.5.0-alpha4`

- The rancher setup is airgapped. 
- Deploy a custom RKE cluster - 3 nodes all roles from Rancher (enabling priv registry)
- local-path-provisioner - used is `image: rancher/local-path-provisioner:v0.0.17` and `image: rancher/local-path-provisioner:v0.0.14`
- After deploying this on the cluster, not able to deploy a PVC using storage class `local-path`
- `wait.go:216: [debug] PersistentVolumeClaim is not bound: cattle-resources-system/backup-restore-operator`

Able to use this on a non airgapped setup.

**Comment by bazzilio** [comment]
@sowmyav27 look to this [PR](https://github.com/rancher/local-path-provisioner/commit/874088575ce38ca3fab3ed774e731c1c3b571dc8).
Seems, in 0.0.18 it should be fixed.
