### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by IlyaSemenov** [rancher/local-path-provisioner#14]
local-path-provisioner is one of the most CPU consuming processes in my cluster:

![image](https://user-images.githubusercontent.com/128121/56510056-e2e6a200-6552-11e9-9457-5b67c9fab202.png)

It seemingly ate 20 minutes of CPU time in just 22 hours:

```
local-path-storage   local-path-provisioner-5fbd477b57-mpg4s    1/1     Running     5          22h
```

During that time, it only created 3 PV's:

```
❯ k logs -n local-path-storage local-path-provisioner-5fbd477b57-mpg4s
time="2019-04-22T03:00:46Z" level=debug msg="Applied config: {\"nodePathMap\":[{\"node\":\"DEFAULT_PATH_FOR_NON_LISTED_NODES\",\"paths\":[\"/opt/local-path-provisioner\"]}]}"
time="2019-04-22T03:00:46Z" level=debug msg="Provisioner started"
time="2019-04-22T05:13:19Z" level=debug msg="config doesn't contain node kube0, use DEFAULT_PATH_FOR_NON_LISTED_NODES instead"
time="2019-04-22T05:13:19Z" level=info msg="Creating volume pvc-5782375f-64bd-11e9-a240-525400a0c459 at kube0:/opt/local-path-provisioner/pvc-5782375f-64bd-11e9-a240-525400a0c459"
time="2019-04-22T05:13:25Z" level=info msg="Volume pvc-5782375f-64bd-11e9-a240-525400a0c459 has been created on kube0:/opt/local-path-provisioner/pvc-5782375f-64bd-11e9-a240-525400a0c459"
time="2019-04-22T10:37:15Z" level=info msg="Deleting volume pvc-5782375f-64bd-11e9-a240-525400a0c459 at kube0:/opt/local-path-provisioner/pvc-5782375f-64bd-11e9-a240-525400a0c459"
time="2019-04-22T10:37:19Z" level=info msg="Volume pvc-5782375f-64bd-11e9-a240-525400a0c459 has been deleted on kube0:/opt/local-path-provisioner/pvc-5782375f-64bd-11e9-a240-525400a0c459"
time="2019-04-22T10:38:20Z" level=debug msg="config doesn't contain node kube0, use DEFAULT_PATH_FOR_NON_LISTED_NODES instead"
time="2019-04-22T10:38:20Z" level=info msg="Creating volume pvc-bee28903-64ea-11e9-a240-525400a0c459 at kube0:/opt/local-path-provisioner/pvc-bee28903-64ea-11e9-a240-525400a0c459"
time="2019-04-22T10:38:24Z" level=info msg="Volume pvc-bee28903-64ea-11e9-a240-525400a0c459 has been created on kube0:/opt/local-path-provisioner/pvc-bee28903-64ea-11e9-a240-525400a0c459"
time="2019-04-22T11:25:29Z" level=info msg="Deleting volume pvc-bee28903-64ea-11e9-a240-525400a0c459 at kube0:/opt/local-path-provisioner/pvc-bee28903-64ea-11e9-a240-525400a0c459"
time="2019-04-22T11:25:33Z" level=info msg="Volume pvc-bee28903-64ea-11e9-a240-525400a0c459 has been deleted on kube0:/opt/local-path-provisioner/pvc-bee28903-64ea-11e9-a240-525400a0c459"
time="2019-04-22T11:26:18Z" level=debug msg="config doesn't contain node kube0, use DEFAULT_PATH_FOR_NON_LISTED_NODES instead"
time="2019-04-22T11:26:18Z" level=info msg="Creating volume pvc-72a9e446-64f1-11e9-a240-525400a0c459 at kube0:/opt/local-path-provisioner/pvc-72a9e446-64f1-11e9-a240-525400a0c459"
time="2019-04-22T11:26:23Z" level=info msg="Volume pvc-72a9e446-64f1-11e9-a240-525400a0c459 has been created on kube0:/opt/local-path-provisioner/pvc-72a9e446-64f1-11e9-a240-525400a0c459"
```

Any ideas what's the matter? It it doing some kind of suboptimal high frequency polling? It bugs me that my brand new, almost empty single node Kubernetes setup already has LA 0.6 without any load coming towards it.

It was deployed with:

```
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```

without any modifications to the manifest.

**Comment by pagong** [comment]
I have the same experience. 
My single node k3os cluster is running an idle instance of `dokuwiki`.
And `local-path-provisioner` is the top cpu scorer (wiithout having any work to do),
![Screenshot_20190501_213143](https://user-images.githubusercontent.com/4641150/57038012-1b743300-6c59-11e9-9d6d-adb5c6df33da.png)

**Comment by snc** [comment]
Same problem here:

![grafik](https://user-images.githubusercontent.com/216730/57058824-3c1ca700-6cb2-11e9-9e25-1d39e17ccc6a.png)

After a reboot the CPU usage is ok for some time, then again rising.

**Comment by ninuxch** [comment]
I had the same with version 0.0.6. The upgrade to version 0.0.7 helped so far.

**Comment by yasker** [comment]
I will look into this issue.

**Comment by yasker** [comment]
Give v0.0.8 a try to see if solve the problem.

**Comment by IlyaSemenov** [comment]
It's definitely better now, showing 0.3-0.5% CPU on average (and without "bursts" every 30 sec as I could have thought by looking at the commit). Aggregated CPU usage has also improved, it has been 1 cpu second for the first 4m 30s of real time.

I upgraded from 0.0.6 to 0.0.8 directly so not sure which version brought the actual fix.

Thank you for addressing the problem anyway.

**Comment by NicklasWallgren** [comment]
Still an issue with rancher/local-path-provisioner:v0.0.9.

k3s crictl stats
```
CONTAINER           CPU %               MEM                 DISK                INODES
076e4ef48abe       25.04               44.45MB             39.09kB             13
```

The cluster is only running the https://github.com/helm/charts/tree/master/stable/prometheus-operator I guess it's related to the metrics polling.
