### ISSUE TITLE
Add drain for PVs

### ISSUE THREAD

**Issue by whiterm** [rancher/local-path-provisioner#141]
Is it possible to add a mechanism that will automatically copy PV with data between nodes? For example, DevOps wanted to remove a node from the cluster, first called the command "kubectl drain worker-1" and then set the annotation for all PVs on this node "drain-pv: true", and after the local-path-provisioner will transfer PVs with data from the old node to the new one.

**Comment by yasker** [comment]
That's assuming you have a reliable mechanism to copy things over... It would be more than a single local path provisioner. Maybe Longhorn (https://longhorn.io) fits your use case better.
