### ISSUE TITLE
Expect for the new release and the docker image!

### ISSUE THREAD

**Issue by will-beta** [rancher/local-path-provisioner#143]
Current release version is still v0.0.17 which doesn't support the flag `-service-account-name` and the helm chart on the `master` branch.

Also, wondering if there’s plan to create an official helm chart repo to make the chart visible on [helm chart hub](https://hub.helm.sh)?

**Comment by alekc** [comment]
Well, it kind of makes sense. Since there was no official release yet, you should use the helm chart from https://github.com/rancher/local-path-provisioner/tree/v0.0.17/deploy

**Comment by yasker** [comment]
I will get a new release out next week. Sorry for the delay. I was busy with Longhorn and other projects for the past few weeks.

**Comment by will-beta** [comment]
@yasker what about the chart repo thing?

**Comment by yasker** [comment]
v0.0.18 has been released with the new chart and image.

In the future, we will use the `dev` branch for the development so it won't affect the stability of the `master` branch.

**Comment by will-beta** [comment]
> v0.0.18 has been released with the new chart and image.
> 
> In the future, we will use the `dev` branch for the development so it won't affect the stability of the `master` branch.

nice work!
what about the chart repo thing?

**Comment by yasker** [comment]
The chart repo is still tracking at https://github.com/rancher/local-path-provisioner/issues/89 . I haven't got time to check it yet. It will need some automation process to package and publish the chart.
