### ISSUE TITLE
Compatibility with k8s 1.20.0

### ISSUE THREAD

**Issue by immanuelfodor** [rancher/local-path-provisioner#168]
The hostPath provisioner project has run into a major issue: https://github.com/rimusz/hostpath-provisioner/issues/8

NFS provisioner, too: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25  
They might have a solution though: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/26

Is the Local Path Provisioner affected by the same problem, or is it safe to use on k8s 1.20.0+?

**Comment by innobead** [comment]
> The hostPath provisioner project has run into a major issue: https://github.com/rimusz/hostpath-provisioner/issues/8
> 
> 
> 
> NFS provisioner, too: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/issues/25  
> 
> They might have a solution though: https://github.com/kubernetes-sigs/nfs-subdir-external-provisioner/pull/26
> 
> 
> 
> Is the Local Path Provisioner affected by the same problem, or is it safe to use on k8s 1.20.0+?

client-go 0.17.1 currently used here, so the selflink issue should not be impacted. It will be good if u give a try, then share the result then.

ref: https://github.com/kubernetes/kubernetes/issues/94660#issuecomment-689887045

**Comment by immanuelfodor** [comment]
Thanks for the info, it's good to hear!
