### ISSUE TITLE
Fix manager termination

### ISSUE THREAD

**Issue by mgoltzsche** [rancher/local-path-provisioner#179]
The manager does not terminate properly but keeps hanging until it gets killed.

Within the cluster this makes Deployment updates take more time and during local development one cannot simply terminate the manager using ctrl+c but must kill it explicitly.

**Comment by mgoltzsche** [comment]
To reproduce it, [start the local-path-provisioner binary](https://github.com/rancher/local-path-provisioner#debug-1) and try terminating it using Ctrl+c - it won't stop but logs `stop watching config file` and keeps hanging [here](https://github.com/rancher/local-path-provisioner/blob/v0.0.21/main.go#L237).
Therefore it seems to be an issue with [sig-storage-lib-external-provisioner](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner).

**Comment by mgoltzsche** [comment]
I updated the storage library dependency with #237 but it doesn't solve the termination issue unfortunately.

**Comment by rorosen** [comment]
Is there any update? I'm experiencing the same issue. Happy to live with the workaround for now though.

**Comment by derekbit** [comment]
> Is there any update? I'm experiencing the same issue. Happy to live with the workaround for now though.

@rorosen 
Currently, I cannot reproduce it for now.
If possible, can you provide the steps to reproduce?

**Comment by superherointj** [comment]
I have experienced this issue myself. And other users have also reported about it at downstream.

As the upgrade of [sig-storage-lib-external-provisioner](https://github.com/kubernetes-sigs/sig-storage-lib-external-provisioner/releases/tag/v10.0.0) solves the issue. Is there something blocking the upgrade?
