### ISSUE TITLE
How can I delete deployment local-path-provisioner  in  kue-system  namespace

### ISSUE THREAD

**Issue by maxianwei** [rancher/local-path-provisioner#191]
Environmental Info:
K3s Version:
 v1.20.6+k3s1

I deleted it use this command:
kubectl delete  deploy local-path-provisioner  -nkube-system

but when I restarted the k3s.service by systemctl restart k3s.service, It's recreated again.

so How can I delete deployment local-path-provisioner  in  kue-system  namespace.

**Comment by ebrianne** [comment]
You need to delete the manifest in `/var/lib/rancher/k3s/manifests` and add the flag `--disable local-storage` to your k3s service.

**Comment by maxianwei** [comment]
thanks @ebrianne
