### ISSUE TITLE
Cannot create volume by local-path-provisioner 

### ISSUE THREAD

**Issue by maxianwei** [rancher/local-path-provisioner#192]
os:  ubuntu20.04
platform:  v1.20.6+k3s1
provisioner version:  v0.0.19

root@w:~/init/deploy# kubectl get  po
...
video-cbccb664-b2hmb                      0/1     Pending             0          2m35s
video-mqtt-6bb5884f57-wn6x8          0/1     ContainerCreating   0          2m35s

root@w:~/init/deploy# kubectl get po  -nkube-system
...
helper-pod-create-pvc-b3ce46c6-8b3a-4d89-ae3b-39ef6f904d9e   0/1     ContainerCreating   0          2m1s

root@w:~/init/deploy# kubectl logs  -nkube-system local-path-provisioner-5ff76fc89d-bbq6r
W0526 07:28:04.802207       1 controller.go:893] Retrying syncing claim "b3ce46c6-8b3a-4d89-ae3b-39ef6f904d9e" because failures 1 < threshold 15
E0526 07:28:04.802274       1 controller.go:913] error syncing claim "b3ce46c6-8b3a-4d89-ae3b-39ef6f904d9e": failed to provision volume with StorageClass "local-path": failed to create volume pvc-b3ce46c6-8b3a-4d89-ae3b-39ef6f904d9e: create process timeout after 120 seconds
I0526 07:28:04.802333       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"video-pvc", UID:"b3ce46c6-8b3a-4d89-ae3b-39ef6f904d9e", APIVersion:"v1", ResourceVersion:"640541", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' failed to provision volume with StorageClass "local-path": failed to create volume pvc-b3ce46c6-8b3a-4d89-ae3b-39ef6f904d9e: create process timeout after 120 seconds

root@w:~/init/deploy# kubectl get pvc
redis-pvc           Bound     pvc-64234644-9f75-48d7-963b-e07699cb31e7   20Gi       RWO            local-path     93m
...
village-pvc         Pending                                                                        local-path     14m
video-pvc           Pending                                                                        local-path     14m

Can anyone help me

**Comment by Jeremy-boo** [comment]
I had the same problem

**Comment by derekbit** [comment]
@maxianwei @Jeremy-boo 
The helper pod cannot enter the `Succeeded` state.
If you encounter the timeout again, can you check the status and log of the helper pod?
```
kubectl -n local-path-storage get pods
kubectl -n local-path-storage describe pod <helper-pod>
kubectl -n local-path-storage logs pod <helper-pod>
```

**Comment by lazywhite** [comment]
> @maxianwei @Jeremy-boo The timeout is due to that the helper pod cannot enter the `Succeeded` state. If you encounter the timeout again, can you check the status and log of the helper pod?
> 
> ```
> kubectl -n local-path-storage get pods
> kubectl -n local-path-storage describe pod <helper-pod>
> kubectl -n local-path-storage logs pod <helper-pod>
> ```

In my case,  helper pod will use rancher/mirrored-library-busybox:1.34.1,  but can't pull this image because of dns name resolve

**Comment by derekbit** [comment]
> In my case, helper pod will use rancher/mirrored-library-busybox:1.34.1, but can't pull this image because of dns name resolve

@lazywhite 
One solution is to replace the helper pod https://github.com/rancher/local-path-provisioner/blob/master/main.go#L96.
