### ISSUE TITLE
v0.0.20 tag uses v0.0.19 image

### ISSUE THREAD

**Issue by damoon** [rancher/local-path-provisioner#202]
the file https://github.com/rancher/local-path-provisioner/blob/v0.0.20/deploy/local-path-storage.yaml
and the chart in https://github.com/rancher/local-path-provisioner/tree/v0.0.20/deploy/chart
use the image of release v0.0.19

would it be possible to update the docker image tags to v0.0.21 and after that release the git tag v0.0.21?
this would allow update bots like renovate to pick up the fix.

**Comment by innobead** [comment]
This was resolved with the latest update. Thank you for reporting!

**Comment by damoon** [comment]
this breaks an expected behavior for renovate (an update bot).
because it already processed the v0.0.20 update and now ignores the tag that overwrites the original v0.0.20.
