### ISSUE TITLE
pvc provision does not create more then 4 helper PODs at the time 

### ISSUE THREAD

**Issue by talcoh2x** [rancher/local-path-provisioner#214]
Hi, maybe you can help me.
I'm using with local-path-provisioner and I really love it :)
my main problem is that once I'm creating 16/20 differents PVC  ( one pvc for each worker  ) I can see that in MAX i have 4 helper PODs . means that I block on 4 POD's creation each time.
there is a limit or something like that in k8s?
what can be the reason for that ?

**Comment by skyoo2003** [comment]
@talcoh2x 

The PR https://github.com/rancher/local-path-provisioner/pull/222 added a flag like '--worker-threads' to change provisioning concurrency. so, you can test it after the feature is released.

**Comment by derekbit** [comment]
Already merged #222.
