### ISSUE TITLE
Bad behavior when k8s nodes are removed by the cluster auto-scaler

### ISSUE THREAD

**Issue by jimdickinson** [rancher/local-path-provisioner#215]
When the following events happen, we see "junk" PV objects build up in our Kubernetes clusters...

- Use local-path storage class with a statefulset, scale it up
- The cluster autoscaler brings in new nodes, we get local-path PVs on those nodes
- Scale down the statefulset to zero replicas
- The cluster autoscaler removes the extra k8s worker nodes - this is fine, we do not need the data on disk
- The PVC object gets deleted by some automation before we scale up or delete the statefulset

local-path-provisioner attempts to clean up the PV during PVC deletion, but it can't start a pod on a node that no longer exists. It gives up after one minute.

Is it possible to fix the issue in the local-path-provisioner code? For now we've implemented a work around to spot this case and delete the PVs that have a node affinity for a node that's left the cluster.

**Comment by iaroslav-nakonechnikov** [comment]
with 0.22 this is still actual issue. 

if node gets cycled (terminated, and new one started) - pvc is not being recreated, which leads to service outage. pods can't start with old pvc, because node was deleted.

**Comment by oblogic7** [comment]
We are running into this same issue with spot instances.  Any time a node disappears, pods fail to schedule onto the replacement due to node volume affinity.  The pod wants to be scheduled where the volume is available, but it is no longer available since the node is gone.  

I think the provisioner needs to monitor node list and clean up any volumes for a node when it is no longer available.

**Comment by joejulian** [comment]
This is also true when a cloud VM fails and is subsequently removed from Nodes. The pods using the PV assigned to the deleted node will remain unschedulable.

I believe there should be a configuration option to allow the automatic deletion of PVs that are assigned to Nodes that are deleted from the cluster.

**Comment by pecigonzalo** [comment]
I think we should re-open here

**Comment by Natanande** [comment]
This is still an issue. Can we re-open the issue?
