### ISSUE TITLE
imagePullPolicy: Always for busybox image will not work in offline enviornments

### ISSUE THREAD

**Issue by digger18** [rancher/local-path-provisioner#22]
The default imagePullPolicy for the busybox helper image which creates the PVC directory on the host is set to "Always".
There must be an option to set it to "IfNotPresent" for offline/airgap environments.

**Comment by yasker** [comment]
We've updated the code to make sure it only pulls `IfNotPresent`.

Seems it's due to the helper image is `busybox` with default `latest` tag instead of a specific version. Before the next release, can you try to use a different helper image, e.g. `busybox:1` to see if it's always pulling?

**Comment by digger18** [comment]
Where can I change the helper image tag?
Do I need to compile the Go code for that check? (I have no idea how to do that)

**Comment by yasker** [comment]
No, you don't need to recompile.

You can just redeploy the provisioner adding `--helper-image` parameter here: https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml#L71

e.g. (untested)

```
        command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        - --helper-image
        - busybox:1
```

**Comment by dorsany** [comment]
Hi @yasker ,
When will you create a new docker tag for the commit 431c704 ?

**Comment by dorsany** [comment]
any update @yasker ?

**Comment by yasker** [comment]
@dorsany @digger18 We've released v0.0.9 to include the fix. Cheers!

**Comment by priyavj08** [comment]
hi,
Can I give an alpine image instead busybox for helper image?
     
thanks and appreciate your reply on this

**Comment by yasker** [comment]
You can change that by adding `--helper-image` in the command line in the yaml.

https://github.com/rancher/local-path-provisioner/blob/master/main.go#L80

**Comment by priyavj08** [comment]
thanks @yasker 
so can I give

 command:
        - local-path-provisioner
        - --debug
        - start
        - --config
        - /etc/config/config.json
        - --helper-image
        - alpine:3.11.3
