### ISSUE TITLE
create directory if missing

### ISSUE THREAD

**Issue by hlacikd** [rancher/local-path-provisioner#221]
Hello,

I have 2 nodes cluster on jetson arm64 platform. OS is on USB flash disk.

I am facing current situation :
local path provisioner will create directory (in my case /data) to fullfill pvc and create pv (bound).
Deployment using this persistent volume will start working.

Someone will accidentally missmatch USB flash disks . OS will start as well as k3s. However deployment will fail (volume will be mounted as read only) because logically that directory created by local path provisioner is not existing on different node.

I would expect/like to have it autocreated, so already deployed PV/PVC will work. Issue is, that PV still reports as BOUND , but thats not true.

**Comment by iaroslav-nakonechnikov** [comment]
with 0.22 this is already working as subject says. 

so looks like issue may be closed
