### ISSUE TITLE
Provisioner on k3s switches namespace, config after reboot

### ISSUE THREAD

**Issue by samstride** [rancher/local-path-provisioner#232]
Hi,

Thanks for maintaining this repo.

I have installed the provisioner on a single node `k3s` cluster (home lab) using:

```sh
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
```

The provisioner originally installs itself in namespace `local-path-storage`.

However, after a node restart (power outage), the provisioner has deployments and configs setup in `kube-system` and the original  deployment fails with an error regarding service account permissions. Sorry, don't have the exact message handy.

Thanks.

**Comment by derekbit** [comment]
@samstride 
Can you show the pods in your system by `k get pods -A | grep local-path-provisioner`?
BTW, k3s has already embedded the `local-path-provisioner`, so you can use it directly.

**Comment by samstride** [comment]
@derekbit , thanks for responding.

When I installed `k3s`, don't think the local provisioner got installed.

I reinstalled the provisioner in `kube-system` now.

Here is the ouput you requested:

```sh
kubectl get pods -A | grep local-path-provisioner

kube-system            local-path-provisioner-84bb864455-47fv4        1/1     Running     2 (2d16h ago)   13d
```

**Comment by chenyg0911** [comment]
some problem with "v1.22.5+k3s1". I update the local-path-config configmap to use the other disk volume    other than the default patch.  When retart the pods "local-path-provisioner-xxxx", it OK. But when restart the k3s, it restore to default path "/var/lib/rancher/k3s/storage". I also try to update the config under /var/lib/rancher/k3s/server/manifests/local-storage.yaml. the effect is the same, when restart k3s, it also restore to default path.

**Comment by harryzcy** [comment]
@chenyg0911 The default path in k3s is set by `--default-local-storage-path` cli argument when starting k3s. If the argument is omitted, it's defaulted to "/var/lib/rancher/k3s/storage".

**Comment by siemendev** [comment]
For everyone stumbling over this issue: The [config file](https://docs.k3s.io/installation/configuration#configuration-file) seems to work in a way where all properties from the yaml are converted to arguments for the k3s binary invocation.

This means, that you can create `/etc/rancher/k3s/config.yaml` with the following content:
```yaml
default-local-storage-path: "/opt/local-path-provisioner"
```

And after restarting the k3s service your config map should be updated with `/opt/local-path-provisioner` as a default path.
