### ISSUE TITLE
Request: upgrade to v0.0.22

### ISSUE THREAD

**Issue by pzeinlinger** [rancher/local-path-provisioner#235]
The merge of #176 allows using this project for zfs backed pvs. In my opinion, this justifies a version bump. 
What's your take on a new release @derekbit ? :smile:

**Comment by derekbit** [comment]
@pzeinlinger 
I will release 0.022 by the end of March.

**Comment by pzeinlinger** [comment]
Thanks for the quick response. 😊
I’ll close this for now
