### ISSUE TITLE
StorageClass CSI compatible

### ISSUE THREAD

**Issue by JBaptisme33** [rancher/local-path-provisioner#239]
Hello,

Thanks for work.
Is there a way to provider a CSI storageclass compatible with local-path ?

Aim goal is to support Snapshots (for Velero full backups since Restic mode is KO with local-path provisionner and hostPath mode)

I've already install snapshot-controller, build velero with right CSI conf. 
Unfortunately, all my k3s PVC are related to local-path storageclass with is not  a CSI-one compatible. Is to possible to use local-path + CSI ?

Thanks

**Comment by derekbit** [comment]
For the backup with velero, you can refer to https://github.com/rancher/local-path-provisioner/issues/85.
I will check it when I am free. :)

**Comment by AnthonyEnr1quez** [comment]
@derekbit possibly can be closed due to #260?

**Comment by derekbit** [comment]
@AnthonyEnr1quez 
Yes.

Close it. Feel free to open it if there is any issue. Thank you.
