### ISSUE TITLE
unable to create a pv due to VOL_DIR: parameter not set

### ISSUE THREAD

**Issue by zMcKracken** [rancher/local-path-provisioner#240]
I'm running rke2 version v1.22.7+rke2r2 in 3 nodes. Today I decide to reinstall my application and I'm not able to do it anymore due to a problem in claiming PV.
I have had never this problems before, and I think is due to an update on local-path-provisioner but I'm not sure I'm still a newbie about kube.

Anyway these are the commands I run before installing my solution:

    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml
    kubectl patch storageclass local-path -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

I omitted metallb. Then as a test I try to install the test you specified:

    kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pvc/pvc.yaml
    kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pod/pod.yaml

What I see is that the pvc stays in a PENDING status, then I check the pod creation in local-path-storage namespace and I see that the helper-pod-create-pvc-xxxx goes in error.
I try to get some logs and the only thing I was able to grab is this:

     kubectl -n local-path-storage logs helper-pod-create-pvc-dd8cecf3-d65b-48f7-9e04-d56a20573f8e -f
    /script/setup: line 3: VOL_DIR: parameter not set

So it seems VOL_DIR is not set for whatever reason. But I never did a custom configuration, it always starts without problem, and to be honest I don't know what put in VOL_DIR env variable and where.
I tried also to reinstall a new fresh rke2 but same problem

**Comment by derekbit** [comment]
Hello, I'm fixing the problem.
Please use v0.0.21 https://github.com/rancher/local-path-provisioner.git, thanks.

**Comment by vincent-pli** [comment]
`kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.21/deploy/local-path-storage.yaml`

I tested it ,works well.

**Comment by derekbit** [comment]
Hello all,
The deploy manifest in master branch is fixed.
The master branch is for development, so please use the v0.0.x (stable release) for production use.
