### ISSUE TITLE
[Question] fsGroup Support

### ISSUE THREAD

**Issue by sushiMix** [rancher/local-path-provisioner#249]
I read the interesting ticket #41 about it. It seems the fsGroup can't be natively supported.
I dig a bit in the kubernetes PersitentVolumes and found that using local (https://kubernetes.io/docs/concepts/storage/volumes/#local since kubernetes 1.14) instead of hostPath will allow Kubelet to manage the fsGroup support instead of trying to implement a specific CSI for hostPath. https://github.com/kubernetes/kubernetes/blob/3bef1692ef2f4a8af87f03599303dbe794493048/pkg/volume/local/local.go#L612
I found that other provisioner use the local entry but does not provide the great flexibility provided by the setup/teardown ConfigMap :).

Is the usage of local instead of hostPath can be a possibility for this provisioner ?

**Comment by benzman81** [comment]
Just tried Local Path Provisioner v0.0.23 and with the annotation it works (see examples).

**Comment by derekbit** [comment]
Thanks for the feedback.
Close it. Feel free to open it if there is any issue.
