### ISSUE TITLE
Storage capacity support

### ISSUE THREAD

**Issue by heyu1207** [rancher/local-path-provisioner#250]
Can local-path-provisioner support the strorage capacity tracking?
I can't use kubectl to list the CSIStorageCapacity resource which is mentioned by the docs of kubernetes: [https://kubernetes.io/docs/concepts/storage/storage-capacity/](url)

**Comment by derekbit** [comment]
Need more investigation. But the first thought came to my mind is that if the volumes on the same filesystem, is it possible to get the storage capacity of each volume correctly?

**Comment by yajo** [comment]
Still relevant
