### ISSUE TITLE
Why did not add cpu, memory limit? Can I add this parameter?

### ISSUE THREAD

**Issue by ChenJhua** [rancher/local-path-provisioner#261]
Hello, I use local-storage here and find that request and limit are not set. I am worried that the resources exceed the limit. I want to ask why there are no such parameters?
Can i add these parameters?
If so, how much CPU and memory are recommended here?

**Comment by ChenJhua** [comment]
@dittos @ereslibre @flavio @ekristen 
Hello, can you help me with my question? thank you

**Comment by derekbit** [comment]
I don't think memory is a concern in local-path provisioner. But smaller CPU limit might result in the mount timeout if system is busy.
