### ISSUE TITLE
[Bug] [Helm] sharedFilesystemPath Missing

### ISSUE THREAD

**Issue by meln5674** [rancher/local-path-provisioner#274]
The config.json field sharedFilesystemPath is [not set in the ConfigMap template](https://github.com/rancher/local-path-provisioner/blob/master/deploy/chart/local-path-provisioner/templates/configmap.yaml#L10), despite [being present in the values.yaml](https://github.com/rancher/local-path-provisioner/blob/master/deploy/chart/local-path-provisioner/values.yaml#L67). This means that instances deployed by helm cannot use the ReadWriteMany access mode.

**Comment by derekbit** [comment]
Thank you for the fix. I think we should generate the deply manifest from the heml chart to avoid this kind of bug in the future

**Comment by niscinfo** [comment]
Hi, 
I have the same issue in v0.0.23. it ignores the sharedFileSystemPath parameter, and as nodePathMap is set to [] , the storageclass doesnt work. 
Thanks for the fix, hope it will be soon included. 

Regards,
