### ISSUE TITLE
Static Persistence to create oracle database failed using oracle database operator

### ISSUE THREAD

**Issue by johnwuwuwuwu** [rancher/local-path-provisioner#276]
I am using oracle database operator to create a database. Using Dynamic Persistence I can create database normally. But with Static Persistence, I am unable to create the database. I first create the PVC using the example PVC.YAML and POD.YAML. then I change the volumeName of singleinstancedatabase.yaml to volv. but the creation fails. I have tried pvc-041b78a4-74c4-4ad5-8097-74163bd9af44_default_local-path-pvc, local-path-pvc, volume-test. but all unsuccessful
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m35s  default-scheduler  0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.

**Comment by derekbit** [comment]
Looks some settings wrong in your deploy manifest.
If the issue continued, please provide us the manifest for further investigation.
