### ISSUE TITLE
helm chart: helperPod - fix documentation or fix back setup (better)

### ISSUE THREAD

**Issue by cr1st1p** [rancher/local-path-provisioner#281]
It looks like at a certain point you removed the possibility to completely define the helper pod definition, while you actually kept the helm chart's README.md still mentioning it.
Please do  one of:
a) fix the README.md and document helperImage value (and remove configmap.helperPod),
b)  revert back that change  (7a557125c7bf523d51fc55510fc5478268607fcc)
c) allow adding helper pod annotations

Preferrably b) or c). Reason: under istio, I really need to add an annotation, so that the pod stops.

**Comment by cr1st1p** [comment]
For c), maybe add something along (untested if not defined):
....
      name: helper-pod
      {{ if .Values.helperImage.annotations }}
      annotations:
{{ .Values.helperImage.annotations | toYaml | nindent 8  }}
      {{ end }}
    spec:
....

**Comment by justusbunsi** [comment]
My 2 ct:

It would be great if we were at least able to customize pod name and/or pod namespace. Preferably the whole template 😉.
Imaging having multiple provisions with different settings in the same cluster. One maybe persists data and the other is fully ephemeral. At some point in time both provisions might provision a PV at the very same time. That's when the static pod name will create conflicts.

**Comment by derekbit** [comment]
> For c), maybe add something along (untested if not defined): .... name: helper-pod {{ if .Values.helperImage.annotations }} annotations: {{ .Values.helperImage.annotations | toYaml | nindent 8 }} {{ end }} spec: ....

@cr1st1p @justusbunsi 

Welcome to submit a PR addressing the issue. Many thanks.
