### ISSUE TITLE
Issue with Velero backup 

### ISSUE THREAD

**Issue by DineshRajj** [rancher/local-path-provisioner#286]
I am using the latest version of rancher Local path provisioner   I am trying to backup pvc it is getting backed-up without files? If I restore no files are there. Is this the behaviour?

**Comment by derekbit** [comment]
What's your volume type? hostpath or local?

**Comment by DineshRajj** [comment]
> What's your volume type? hostpath or local?

local-path

**Comment by derekbit** [comment]
IIRC, some users reported the success of the backup using velero.
What's your steps?

**Comment by DineshRajj** [comment]
velero version  v1.9.3
rancher local path provisoner verison v0.0.23
Kubernetes v1.23
PVC access mode : ReadWriteOnce
velero install \
    --provider aws \
    --plugins velero/velero-plugin-for-aws:v1.2.1 \
    --bucket velero \
    --secret-file ./credentials-velero \
    --use-volume-snapshots=false \
    --use-node-agent \
     --default-volumes-to-fs-backup \
    --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://<url>/ 
   
   
   velero backup create test-backup --include-namespaces test --default-volumes-to-fs-backup --wait
   
   velero restore create --from-backup test-backup
   
   After restoring I can see the pv and pvcs  restored successfully but no data inside

**Comment by derekbit** [comment]
@DineshRajj
Thank you. I will check it later.

**Comment by derekbit** [comment]
@DineshRajj 
Sorry. I'm busy in working on longhorn project these days.
I hope I could check it during the weekend or next week.

@fabioandreola Do you have idea for this? I saw you reported the success of the backup using velero in the [comment](https://github.com/rancher/local-path-provisioner/pull/260#issuecomment-1293263036).

**Comment by derekbit** [comment]
@DineshRajj 
Just tried the backup and restore of `local-volume` type volumes using velero. Works well and the data are resored as expected.
You might need to check the velero log and check what happened.

**Comment by DineshRajj** [comment]
Thanks  @derekbit 

```
time="2022-12-18T18:27:31Z" level=info msg="label \"topology.kubernetes.io/zone\" is not present on PersistentVolume, checking deprecated label..." backup=velero/busychain8 logSource="pkg/backup/item_backupper.go:445" name=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c namespace= persistentVolume=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c resource=persistentvolumes
time="2022-12-18T18:27:31Z" level=info msg="label \"failure-domain.beta.kubernetes.io/zone\" is not present on PersistentVolume" backup=velero/busychain8 logSource="pkg/backup/item_backupper.go:449" name=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c namespace= persistentVolume=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c resource=persistentvolumes
time="2022-12-18T18:27:31Z" level=info msg="zone info not available in nodeAffinity requirements" backup=velero/busychain8 logSource="pkg/backup/item_backupper.go:454" name=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c namespace= persistentVolume=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c resource=persistentvolumes
time="2022-12-18T18:27:31Z" level=info msg="Persistent volume is not a supported volume type for snapshots, skipping." backup=velero/busychain8 logSource="pkg/backup/item_backupper.go:489" name=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c namespace= persistentVolume=pvc-7815f09c-598b-4511-93b9-4a2aadeae29c resource=persistentvolumes

```

I am seeing the above in the logs  **Persistent volume is not a supported volume type for snapshots, skipping.**. Every thing looks fine.  Don't know what I am missing

**Comment by derekbit** [comment]
Can you show the info `kubectl get pvc <pvc name> -o yaml` and `kubectl get pvc <pv name> -o yaml`?

**Comment by DineshRajj** [comment]
@derekbit   Here it is.

kubectl get pvc -o yaml

`
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{"volumeType":"local"},"name":"peer6-busy-pvc","namespace":"busychain"},"spec":{"accessModes":["ReadWriteOnce"],"resources":{"requests":{"storage":"2Gi"}},"storageClassName":"local-path"}}
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
      volume.kubernetes.io/selected-node: master-fed6ebc8664f
      volume.kubernetes.io/storage-provisioner: rancher.io/local-path
      volumeType: local
    creationTimestamp: "2022-12-18T18:28:18Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      velero.io/backup-name: busychain8
      velero.io/restore-name: busychain8-20221218182809
    name: peer6-busy-pvc
    namespace: busychain
    resourceVersion: "4320256"
    uid: 23a587f1-2db2-46fe-aff9-c61d3fc7d289
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
    storageClassName: local-path
    volumeMode: Filesystem
    volumeName: pvc-23a587f1-2db2-46fe-aff9-c61d3fc7d289
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
`
kubectl get pv <pv name> -o yaml
`apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    annotations:
      pv.kubernetes.io/provisioned-by: rancher.io/local-path
    creationTimestamp: "2022-12-18T18:28:22Z"
    finalizers:
    - kubernetes.io/pv-protection
    name: pvc-23a587f1-2db2-46fe-aff9-c61d3fc7d289
    resourceVersion: "4320253"
    uid: 9349b1bf-db7e-4576-a0dd-7a49988ff591
  spec:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 2Gi
    claimRef:
      apiVersion: v1
      kind: PersistentVolumeClaim
      name: peer6-busy-pvc
      namespace: busychain
      resourceVersion: "4320176"
      uid: 23a587f1-2db2-46fe-aff9-c61d3fc7d289
    local:
      path: /opt/local-path-provisioner/pvc-23a587f1-2db2-46fe-aff9-c61d3fc7d289_busychain_peer6-busy-pvc
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - master-fed6ebc8664f
    persistentVolumeReclaimPolicy: Delete
    storageClassName: local-path
    volumeMode: Filesystem
  status:
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
`

Appreciate all your help with this. Cheers

**Comment by DineshRajj** [comment]
Hey @derekbit  did you get a chance to look at the above config

**Comment by derekbit** [comment]
@DineshRajj 
The configuration (volumeType: local) is correct. The only difference in my side is I used velero v1.10.0.

**Comment by DineshRajj** [comment]
Not sure. What is wrong? Anyway thanks for investigating it @derekbit

**Comment by DineshRajj** [comment]
> > Not sure. What is wrong? Anyway thanks for investigating it @derekbit
> 
> I will provide my steps for your reference later. Then, you can check if it can work and figure out what happened.

Sure. That is going to help. Thanks.

**Comment by DineshRajj** [comment]
> > > Not sure. What is wrong? Anyway thanks for investigating it @derekbit
> > 
> > I will provide my steps for your reference later. Then, you can check if it can work and figure out what happened.
> 
> Sure. That is going to help. Thanks.

@derekbit  Please share steps you followed to backup PVS.. Whenever you get a chance..Thanks 👍

**Comment by derekbit** [comment]
@DineshRajj 
Sorry for late reply. Please refer to my [note](https://github.com/derekbit/longhorn-toolbox/tree/velero-v1.10.0/velero). Hope it is helpful.

**Comment by DineshRajj** [comment]
> @DineshRajj 
> Sorry for late reply. Please refer to my [note](https://github.com/derekbit/longhorn-toolbox/tree/velero-v1.10.0/velero). Hope it is helpful. 

No worries.. Thanks.. I will try and update 👍.
