### ISSUE TITLE
xfs quota example helper pod failure

### ISSUE THREAD

**Issue by PeaceRebel** [rancher/local-path-provisioner#288]
The pods fails with `Error: failed to prepare subPath for volumeMount "xfs-quota-projects" of container "helper-pod"`

`projects` file is created in `/etc`

**Comment by derekbit** [comment]
Welcome to submit a PR for fixing the issue.

cc @liupeng0518 Probably releated to the [PR](https://github.com/rancher/local-path-provisioner/pull/278)
