### ISSUE TITLE
Update sigs.k8s.io/sig-storage-lib-external-provisioner dependency to v8.0.0+

### ISSUE THREAD

**Issue by mengjiao-liu** [rancher/local-path-provisioner#292]
beta annotation `volume.beta.kubernetes.io/storage-provisioner` on PVC is deprecated. 
https://kubernetes.io/docs/reference/labels-annotations-taints/#volume-beta-kubernetes-io-storage-provisioner-deprecated

kubernetes repo is about to remove the beta annotation, so please update dependency `sigs.k8s.io/sig-storage-lib-external-provisioner` to v8.0.0 and above to support GA version annotation(volume.kubernetes.io/storage-provisioner ) as soon as possible.

see more details at https://github.com/kubernetes/kubernetes/issues/104760  https://github.com/kubernetes/kubernetes/pull/114804.

**Comment by derekbit** [comment]
Handled in https://github.com/rancher/local-path-provisioner/pull/296

**Comment by derekbit** [comment]
@mengjiao-liu 
Thank you for the feedback. If you have time, feel free to help review it. Appreciated. Thank you.

**Comment by mengjiao-liu** [comment]
PR has been merged. Thanks.
