### ISSUE TITLE
Provisionner not follow the pod claim Node Affinity...

### ISSUE THREAD

**Issue by mcarbonneaux** [rancher/local-path-provisioner#30]
i've a kubernetes cluster of two node.
i've deployed local path provisioner on it.
i deploy a mariadb with node affinity on node A with pv claim using local path provisionner...
but provisionner whant to provisione the pvc on node B in place of node A where the pod are launch (the pod as node A affinity)... and fail by timeout to wait the pvc...

how to force local path provisionner to follow the pod affinity ?

**Comment by yasker** [comment]
Hi, can you try the example at https://github.com/rancher/local-path-provisioner/blob/master/examples/pod-with-node-affinity.yaml ?

**Comment by mcarbonneaux** [comment]
ok i've used nodeName... beceause is intuitive in rancher 2 ui to used that ...

![image](https://user-images.githubusercontent.com/8479023/60771152-c551bf00-a0e3-11e9-8d33-2631b3cdc87b.png)

i've used in place : 
![image](https://user-images.githubusercontent.com/8479023/60771161-f3cf9a00-a0e3-11e9-8864-424ac797177e.png)

and it's work!

**Comment by yasker** [comment]
@mcarbonneaux It's limited by how Kubernetes implemented the local PV. We need to use the selector instead of setting the node name directly get it to work.

Close this issue for now.
