### ISSUE TITLE
Vulnerabilities in v0.0.23

### ISSUE THREAD

**Issue by jocelync1094** [rancher/local-path-provisioner#303]
Hi, there are some vulnerabilities (in libcrypto and libssl) from the currently used alpine version, which has fixes in the later alpine releases. Similarly, there are some vulnerabilities in the golang packages currently in use, such as the text, net, crypto, k8s.io/client-go, k8s.io/apimachinery, and github.com/prometheus/client_golang). These packages also have fixes in recent versions. I was wondering if these will libraries/packages will be upgraded to address the CVEs. Thank you!

**Comment by derekbit** [comment]
Sure. Will update in the upcoming v0.0.24. Thanks for the feedback.

**Comment by jocelync1094** [comment]
Thank you!
