### ISSUE TITLE
unable to start provisioner

### ISSUE THREAD

**Issue by Arryboom** [rancher/local-path-provisioner#330]
installed on bare metall with k3s v1.26.3+k3s1(which now is lastest stable version),with command 
```
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
```
what's weird is that it deployed success and the pod  local-path-provisioner-xxxxxx running normally,after a restart of k3s cluster,the  local-path-provisioner-xxxxx keeps crash,
```
NAMESPACE            NAME                                        READY   STATUS             RESTARTS        AGE
local-path-storage   local-path-provisioner-69945974f5-krrbx     0/1     CrashLoopBackOff   543 (75s ago)   47h
```
but it doesn't affect the normal use of pvc provided by local-path-storage class.all other pod that has pvc mounted that comming from local-path-storage is running normally,

then I full restart the whole k3s cluster again and got this log at first time ,then it goes into crashloop
```
kubectl logs local-path-provisioner-69945974f5-krrbx -n local-path-storage
time="2023-04-21T22:47:45Z" level=fatal msg="Error starting daemon: invalid empty flag helper-pod-file and it also does not exist at ConfigMap local-path-storage/local-path-config with err: configmaps \"local-path-config\" is forbidden: User \"system:serviceaccount:local-path-storage:local-path-provisioner-service-account\" cannot get resource \"configmaps\" in API group \"\" in the namespace \"local-path-storage\"
```

it seems like it cannot access some api in namespace local-path-storage,should I reinstall it to kube-system in k3s?but the offical reference told me to use kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml,and the first line of this yaml conf was name space local-path-storage

**Comment by unclegaara** [comment]
Same issue with k3s.

**Comment by derekbit** [comment]
Is the issue observed in v0.0.23?

**Comment by unclegaara** [comment]
0.0.23 and 0.0.24. Doesn't matter.

**Comment by Arryboom** [comment]
still the same

**Comment by Arryboom** [comment]
wonder if there was a misunderstanding the typical usage of local-path-provisioner there?
my depolyment was typical 3 machine,1 master with 2 worker node

each got 200GB disk available locally(it's 3 separated physical disk,not the same one physical disk ),so by default local-path-provisioner should using /opt/local-path-provisioner path as storage on system

maybe I should using only one physical disk and make sure the content is all the same on all k3s node under /opt/local-path-provisioner path when using local-path-provisioner?I mean like,using a nfs mounted /opt/local-path-provisioner  point to the same one physical disk on all those 3 node,or like multipath/iscsi etc network mount?

**Comment by Arryboom** [comment]
I've using 0.0.23 before and got this issue then migrated to 0.0.24,still the same

**Comment by derekbit** [comment]
@Arryboom 
Thank you for the information. Sorry for the delay because of the longhorn developement. I will start to investigate the issue.

**Comment by derekbit** [comment]
@Arryboom 
Have you disabled local-path-provisioner shipping with `k3s` before installing 0.0.23 or 0.0.24?

**Comment by Arryboom** [comment]
> @Arryboom Have you disabled local-path-provisioner shipping with `k3s` before installing 0.0.23 or 0.0.24?

Oh!
Never know local-path-provisioner shipping with k3s by default,using k8s before so I thought we might need to manually choose one storage solution thus we need install it manually too.


k3s was installed just like offical site with command but disabled servicelb etc to using metallb in my enviroment before
```
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--disable servicelb --disable traefik" sh -s
```

I thought I found some tutorial said local-path-provisioner is great for using local path as storage and ignore the low-level filesystem implementation etc situation,so I installed it using the command as mentioned at the beginning to install it

but,Is the one comming with k3s available for out of <k8s system> namespace?  
I mean is the one comming with k3s by default was a k3s system internal service using only version? the one that's not publicly available to our business running service/pod etc?or it's just the same as the one I manually installed by 


```
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
```

**Comment by derekbit** [comment]
> but,Is the one comming with k3s available for out of namespace?
> I mean is the one comming with k3s by default was a k3s system internal service using only version? the one that's not publicly available to our business running service/pod etc?or it's just the same as the one I manually installed by

Sure. The default local-path provisioner is available for other applications.

If you don't want to use local-path provisioner shipped with k3s, you can disable it by `--disable local-storage` and install it by 
```
kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
```

**Comment by Arryboom** [comment]
> > but,Is the one comming with k3s available for out of namespace?
> > I mean is the one comming with k3s by default was a k3s system internal service using only version? the one that's not publicly available to our business running service/pod etc?or it's just the same as the one I manually installed by
> 
> Sure. The default local-path provisioner is available for other applications.
> 
> If you don't want to use local-path provisioner shipped with k3s, you can disable it by `--disable local-storage` and install it by
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
> ```

Appreciate,
gonna do some research on uninstall the one I manually installed and start using the one coming by default,the crash issue might because of my manually installed one messed up with the one coming by default.

but the cluster,it's kind of "Production Enviroment" now,really don't want to mess it up,Is directly running
```kubectl delete -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml```
to uninstall the one I manually installed is an option?I'm guess this might remove some components(or all components)on the one coming with k3s by default then I better reinstall the whole k3s again?

**Comment by Arryboom** [comment]
> > but,Is the one comming with k3s available for out of namespace?
> > I mean is the one comming with k3s by default was a k3s system internal service using only version? the one that's not publicly available to our business running service/pod etc?or it's just the same as the one I manually installed by
> 
> Sure. The default local-path provisioner is available for other applications.
> 
> If you don't want to use local-path provisioner shipped with k3s, you can disable it by `--disable local-storage` and install it by
> 
> ```
> kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml
> ```

uninstalled the one I manually installed and reinstall k3s again,so we should be using the one coming with k3s bydefault,the problem not appear again,Thanks so much!
