### ISSUE TITLE
Helper Pod always runs in privileged mode

### ISSUE THREAD

**Issue by dihmandrake** [rancher/local-path-provisioner#343]
PR [#295](https://github.com/rancher/local-path-provisioner/pull/295) enforces the helper pod to always run in priviliged mode.

I understand that it helps in some circumstances (i.e. as mentioned with SELinux), but I fail to see the point omitting the feature to configure these settings via the `helperPod.yaml`.
In my understanding this will introduces potential security issues (running in priviliged mode) and will likely be also be prohibited. Also, this fails with any best practice guide.

My suggestion would be to revert the enforced privileged mode in "code" and rather adjust the deployment yaml files. This will leave up to the user to enable or disable priviliged mode for the helper pod and distinctively shows the usage of priviliged (as it was when it was introduced  https://github.com/rancher/local-path-provisioner/pull/127/files#diff-fc1d3532da225d7e818cabd69a275d89c6ada8847e5c90da50c1c7081dc0f071R11).

Could we revert the mentioned PR and try to avoid enforcing privileged mode?

**Comment by ndhil13** [comment]
Yes , facing a similar issue wherein the helper busybox pod runs in privileged and security context over ride in the config map does not work as it is over ridden in code . Any reason why this was done so? Will the non privileged helper box not be able to create local volumes as a normal user?

**Comment by derekbit** [comment]
Revert https://github.com/rancher/local-path-provisioner/pull/295 first and find a better solution for SELinux env.
