### ISSUE TITLE
how to create xfs formatted disks with this?

### ISSUE THREAD

**Issue by pdeva** [rancher/local-path-provisioner#353]
seems the disks are created using `ext4` by default? how to i configure chart to create `xfs` formatted disks?

**Comment by derekbit** [comment]
Well, no. The local-path-provisioner actually creates a folder as a volume on a local filesystem, so you can format the local storage as a `xfs` filesystem for holding volumes.

**Comment by pdeva** [comment]
sure. so the provisioner formats the volume before mounting it right? how do i configure it to format it as xfs instead of ext4

**Comment by derekbit** [comment]
I mean you can prepare a disk, format it to xfs and mount it. Then, add the
mount point to local-path provisioner’s path list.
