### ISSUE TITLE
Possibility to change affinity rules

### ISSUE THREAD

**Issue by dberardo-com** [rancher/local-path-provisioner#356]
Is it possible to define a specific PVC so that the underlying volume can be created/attached on more than one node ? what i mean is basically to change the affinity rule:

* i need to define a localpath for some sort of "cache volume"
* the cache volume does not need to be defined on a specific host
* in fact if a node goes down, i would like the Pod to be able to re-spawn on another node and create the volume there
* once the node comes back up, the older volume can be picked up without no issue

is this possible ?

**Comment by derekbit** [comment]
> i need to define a localpath for some sort of "cache volume"

Do you mean you don't care about the data loss?

**Comment by dberardo-com** [comment]
exactly, i know that 99% of the time the pod and the local volume will reside on the same node, except from when that node is down (1% of the time). in such instance then the pod is allowed to start on another node.

data loss is a minor concern in cache systems, however i would still like this cache to be persisted on a local volume most of the time

**Comment by kghost** [comment]
Is it possible that we can write some setup/teardown scripts to copy/sync data from old node to new node ?

such that pods can be automatically migrated to other nodes.

**Comment by dberardo-com** [comment]
hi there any update?
