### ISSUE TITLE
Persistence Volume Name is dynamic (Eg :pvc-5f9522a8-b900-11e9-b3d4-005056a04e8b)

### ISSUE THREAD

**Issue by AnudeepKumarDonthu** [rancher/local-path-provisioner#37]
Since the k8s local storage doesn't support dynamic provisioning yet, I found the local-file-provisioner from Rancher which seems to fill this gap. Deploying the examples mentioned in the documentation, I see PVs with random names generated:
Example:
NAME                                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
data-exciting-jellyfish-rabbitmq-ha-0   Bound    **pvc-5f9522a8-b900-11e9-b3d4-005056a04e8b**   8Gi        RWO            standard        8m49s
data-exciting-jellyfish-rabbitmq-ha-1   Bound    **pvc-8b201f83-b900-11e9-b3d4-005056a04e8b**   8Gi        RWO            standard        7m36s
data-exciting-jellyfish-rabbitmq-ha-2   Bound    **pvc-b6835ba6-b900-11e9-b3d4-005056a04e8b**   8Gi        RWO            standard        6m23s

On the node, the folder /opt/local-path-provisioner/pvc-e8ade5da-b2bf-11e9-a8b0-d43d7eed0a97/ was generated. It is possible to get the link from PVC to PV. But this make it more complicated, especially when having many PVCs and manually looking in the volume is required for debugging. Or when exporting/importing backups.

I'd like to have more human readable volume name so that I can specify in the pvc file so that later I will know the directory name post creation of PV where my application will store the files

**Comment by yasker** [comment]
Hi @AnudeepKumarDonthu 

Sadly it's totally out of our control. Kubernetes generates the PV name by itself and the storage driver can only accept the name generated by Kubernetes.

It's a common complaint while using any Storage Class and Dynamic Provisioner, unfortunately, we probably cannot do anything about it.

**Comment by AnudeepKumarDonthu** [comment]
Thank you @yasker 

Can you please help me with the way to pass the path dynamically as below, where $MY_HOME is a environment value stored in /etc/environment

Example:
"paths":["/$MY_HOME/mount"]

**Comment by yasker** [comment]
@AnudeepKumarDonthu 

You can change the configuration in https://github.com/rancher/local-path-provisioner#configuration to achieve a similar result. Also, I am not clear what do you mean by using `$MY_HOME` for path. Can you file a feature request and let's discuss there?

I will close this issue for now since we're talking about something else.
