### ISSUE TITLE
E2E test failing due to conflicting PersistentVolume with previous test when volume type is "local"

### ISSUE THREAD

**Issue by kn3609571** [rancher/local-path-provisioner#376]
All resources are deleted at the same time in E2E test.
This prevents the PersistentVolume from being deleted by teardown process.
"Local" volumes won't create underlying directories automatically, so the second and subsequent tests using "local" volumes will fail.

I think the following actions are needed.
1. Separating the PVC and Pod deletion process from the local-path-provisioner deletion process.
2. Changing the name of the PVC for each test.
3. Implementing tests for teardown process.

**Comment by jan-g** [comment]
#416 fixes this
