### ISSUE TITLE
creating multiple storage classes for multiple locations

### ISSUE THREAD

**Issue by ahmadalli** [rancher/local-path-provisioner#38]
I like to have some hostpaths (on all nodes) on `/mnt/b` and some on `/mnt/c`. is it possible for me to create multiple storage classes for multiple locations?

**Comment by hdimitriou** [comment]
Just want to say that this is possible with the current setup. 
You just need a separate provisioner installation and you practically install teh chart 2 times with different config
```
storageClass:
  name: local-path-1
  provisionerName: rancher.io/local-path-1

nodePathMap: [
  {
    "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
    "paths": ["/local-1"]
  }
]
```
and
```
storageClass:
  name: local-path-2
  provisionerName: rancher.io/local-path-2

nodePathMap: [
  {
    "node": "DEFAULT_PATH_FOR_NON_LISTED_NODES",
    "paths": ["/local-2"]
  }
]
```

**Comment by yasker** [comment]
@hdimitriou ha, yeah. I was considering if you use the same provisioner name. Thanks for pointing this out!

**Comment by ahmadalli** [comment]
@hdimitriou great! how does `provisionerName` get assigned? does it have numerical order or can it be customized?

**Comment by yasker** [comment]
@ahmadalli You can set it manually using `--provisioner-name` in the command line, as a parameter for `local-path-provisioner`, e.g. after [`start`](https://github.com/rancher/local-path-provisioner/blob/master/deploy/local-path-storage.yaml#L68)

**Comment by ahmadalli** [comment]
thanks. it worked :)
it would be good to add this to the documentation

**Comment by dorsany** [comment]
so is it considered as a feature request to support 2 `storageClasses` in one `local-path-provisioner` controller to support multiple locations ?
