### ISSUE TITLE
Volume not provisioned when binding type is set to `Immediate`

### ISSUE THREAD

**Issue by roshanirathi** [rancher/local-path-provisioner#386]
PVC is in pending state with error - `configuration error, no node was specified`. This behaviour is seen only when binding type is set to `Immediate`. Volume gets provisioned when set to `WaitForFirstConsumer`. 

As per what I have read online, the reason for this is PodSecurityPolicy was not updated to use local-path. But since PSP is deprecated, what is the alternative solution for it? 

I tried adding namespace labels for ns in which the LPP was deployed and also for the ns in which the PVC was deployed, but that didn't work out.

Versions used:
LPP - 0.25.0
k8s - 1.28.5

**Comment by shkatara** [comment]
Hi Roshni,
I am also getting the same issue. Did you have any luck so far ?

**Comment by MisderGAO** [comment]
Hello,
Same issue for me. 
community k8s 1.28.7

**Comment by roshanirathi** [comment]
Adding node-affinity in persistent volume spec is one way to get it working.
But then it negates the entire point of dynamic provisioning.

**Comment by jackson-chris** [comment]
Can maintainers confirm or deny if using a `VolumeBindingMode` of `Immediate` is currently supported?

**Comment by saulrobe** [comment]
I have the same issue. It seems like it is not supported.
