### ISSUE TITLE
Permission denied on RHEL based OS

### ISSUE THREAD

**Issue by atassis** [rancher/local-path-provisioner#398]
After installing the LPP and initializing the PVC with pod, I receive an error for directory creation via helper:
```shell
mkdir: can't create directory '/data/local-path-provisioner/pvc-7a3c3fd8-6564-4bd6-a655-8a967e000a4b_default_volume-test-pvc': Permission denied
```
To fix it, I had to give SELinux attribute to the directory with command:
```shell
chcon -Rt container_file_t  /data/local-path-provisioner 
```
 I have seen several issues for the same error, but none of them related to the chcon command and RHEL based distributions like Fedora.

**Comment by emilianomaccaferri** [comment]
you saved me a lot of time!

**Comment by atassis** [comment]
Tried to be as clear as possible:) nice to hear that it helped🫶
