### ISSUE TITLE
can't create directory: Permission denied

### ISSUE THREAD

**Issue by aroute** [rancher/local-path-provisioner#418]
Any suggestions?

`mkdir: can't create directory '/opt/local-path-provisioner/pvc-4bcd4bcc-8d82-4d05-a625-b11a1438474a_local-path-storage_local-path-pvc': Permission denied`

`level=info msg="mkdir: can't create directory '/opt/local-path-provisioner/pvc-4bcd4bcc-8d82-4d05-a625-b11a1438474a_local-path-storage_local-path-pvc': Permission denied"`

**Comment by Kampe** [comment]
Seeing the same issues here using the latest 0.0.28 after a restart of one of my nodes
