### ISSUE TITLE
Helm chart version is lagging behind

### ISSUE THREAD

**Issue by dchirikov** [rancher/local-path-provisioner#426]
Hi Team

I found out that helm chart is still signaling 0.0.25 version despite current version of the project is 0.0.27:
https://github.com/rancher/local-path-provisioner/blob/v0.0.27/deploy/chart/local-path-provisioner/Chart.yaml

**Comment by derekbit** [comment]
Thanks for raising the issue. Updated it in https://github.com/rancher/local-path-provisioner/pull/428.
