### ISSUE TITLE
invalid chart reference: validation: chart.metadata.version "master-head" is invalid

### ISSUE THREAD

**Issue by applike-ss** [rancher/local-path-provisioner#436]
When deploying the helm chart via flux2, i do get the error: `invalid chart reference: validation: chart.metadata.version "master-head" is invalid`.

Can/Should we use a proper version scheme here, like SemVer?

**Comment by derekbit** [comment]
Sure.
BTW, can you switch to v0.0.28 instead? master-head is only for development purpose.

**Comment by applike-ss** [comment]
I've opened a PR here: https://github.com/rancher/local-path-provisioner/pull/437

**Comment by applike-ss** [comment]
I switched to referring to the tagged version instead in the GitRepository resource of flux2, closing
