### ISSUE TITLE
Are there any plan to support Windows node?

### ISSUE THREAD

**Issue by jianliang00** [rancher/local-path-provisioner#442]
I have used this project on Windows node, but the helper pod which uses busybox can not run on Windows. So I wonder are there any solution to support Windows?

**Comment by doctorpangloss** [comment]
`hashicorpdev/busybox-windows:ltsc2022` works fine. Rancher just has to make a multi-image manifest.

**Comment by derekbit** [comment]
Thanks @doctorpangloss. Let's make it in v0.0.29.
