### ISSUE TITLE
Storage class configured for shared volumes does not syncronize between nodes

### ISSUE THREAD

**Issue by zad80** [rancher/local-path-provisioner#443]
I've deployed rancher local path provisioner v0.0.28 on a k8s cluster via helm and configured with the configMap options:
~~~yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: local-path-config
  namespace: "{{ .Release.Namespace }}"
data:
  config.json: |-
    {
           "storageClassConfigs":{
             "local-path": {
                    "nodePathMap": [
                    {
                            "node":"DEFAULT_PATH_FOR_NON_LISTED_NODES",
                            "paths":["/opt/local-path-provisioner"]
                    }
                    ]
             },
             "local-path-shared": {
                    "sharedFilesystemPath": "/opt/local-path-provisioner-shared"
             }
            }
    }
  setup: |-
    #!/bin/sh
    set -eu
    mkdir -m 0777 -p "$VOL_DIR"
  teardown: |-
    #!/bin/sh
    set -eu
    rm -rf "$VOL_DIR"
  helperPod.yaml: |-
    apiVersion: v1
    kind: Pod
    metadata:
      name: helper-pod
    spec:
      priorityClassName: system-node-critical
      tolerations:
        - key: node.kubernetes.io/disk-pressure
          operator: Exists
          effect: NoSchedule
      containers:
      - name: helper-pod
        image: busybox
        imagePullPolicy: IfNotPresent
~~~
I've also create the storage class:
~~~yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-shared
provisioner: rancher.io/local-path
volumeBindingMode: Immediate
reclaimPolicy: Delete
~~~
And finally used on a pvc:
~~~yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-vol
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "local-path-shared"
~~~

The main problem is that when I create a pvc the pvc directory is correctly created on all nodes, but the content isn't syncronized. i.e 
A pod on node-1 touch a file named test.txt, but on node-1+X the test.txt files isn't created.

Did I missed something or this is the expected behavior ?

**Comment by hugosxm** [comment]
Hi, 

It is not the role of the local-path-provisioner to sync the data. What you are trying to achieve is not the expected behavior. 
You have to bring your own sync system, either a glusterfs folder, or a NFS share, whatever... Then you mount it on every node and the provisioner will create the folder for you.

**Comment by zad80** [comment]
Thank you. Imho i think there is very little use of this feature in real life. Regards I mark the issue as solved.

**Comment by Xachman** [comment]
Frist of all @zad80 thanks for posting this you helped me sort out an issue setting this up. 

There are use cases where you cant use NFS in unprivileged containers on linux. In this case you can use this by mounting the NFS on the host and then using shared filesystems in the container. In my case I am using incus and a shared filesystem. Either way there are some cases mostly where you cant use NFS where this will apply.
