### ISSUE TITLE
Request for new release

### ISSUE THREAD

**Issue by unguiculus** [rancher/local-path-provisioner#449]
The current release (v0.0.28) has a bunch of critical and high CVEs. The fix has been merged in #435. Can we please get a new release soon? Thanks.

**Comment by derekbit** [comment]
> The current release (v0.0.28) has a bunch of critical and high CVEs. The fix has been merged in #435. Can we please get a new release soon? Thanks.

Yes, we will release v0.0.29 as planned.

**Comment by unguiculus** [comment]
Thanks @derekbit. What does "as planned" mean? Is there a documented release schedule? I was looking around but didn't find anything.

**Comment by derekbit** [comment]
> Thanks @derekbit. What does "as planned" mean? Is there a documented release schedule? I was looking around but didn't find anything.

Originally, our release dates were scheduled for May and October.

However, with the recent[ introduction of image scanning,](https://github.com/rancher/image-scanning/) we will now release updates soon if any CVE issues are found.

Additionally, I integrated [Trivy](https://github.com/rancher/local-path-provisioner/pull/448) last week, which should enable us to release updates more frequently in response to critical issues.
