### ISSUE TITLE
The example : https://github.com/rancher/local-path-provisioner?tab=readme-ov-file#usage is failing

### ISSUE THREAD

**Issue by raphael10-collab** [rancher/local-path-provisioner#456]
The example : https://github.com/rancher/local-path-provisioner?tab=readme-ov-file#usage is failing : 

    raphy@raohy:~/.talos/local-path-provisioner$ kubectl apply -f pod.yaml 
    Warning: would violate PodSecurity "restricted:latest": allowPrivilegeEscalation != false (container "volume-test" must set securityContext.allowPrivilegeEscalation=false), unrestricted capabilities (container "volume-test" must set securityContext.capabilities.drop=["ALL"]), runAsNonRoot != true (pod or container "volume-test" must set securityContext.runAsNonRoot=true), seccompProfile (pod or container "volume-test" must set securityContext.seccompProfile.type to "RuntimeDefault" or "Localhost")
    pod/volume-test created
    raphy@raohy:~/.talos/local-path-provisioner$ 
    raphy@raohy:~/.talos/local-path-provisioner$ kubectl get pv
    No resources found
    raphy@raohy:~/.talos/local-path-provisioner$ kubectl get pvc
    NAME             STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   VOLUMEATTRIBUTESCLASS   AGE
    local-path-pvc   Pending                                      local-path     <unset>                 36s
    raphy@raohy:~/.talos/local-path-provisioner$ kubectl get pod
    NAME          READY   STATUS    RESTARTS   AGE
    volume-test   0/1     Pending   0          37s

**Comment by nfillot** [comment]
@raphael10-collab Talos enables [Pod Security](https://www.talos.dev/v1.8/kubernetes-guides/configuration/pod-security) so you need to configure the plugin or set the `pod-security.kubernetes.io/enforce` label on the namespace
