### ISSUE TITLE
Block volume provisioning

### ISSUE THREAD

**Issue by IanMoroney** [rancher/local-path-provisioner#463]
While trying to use this provisioner to get rook-ceph to install, one of the PVCs that it tries to create wants to use `VolumeMode: Block`.
Is this possible via this local-path-provisioner?
```
version: v0.0.30
```

```
"Failed to provision volume" err="rancher.io/local-path does not support block volume provisioning" 
PVC="rook-ceph/set1-data-0pm7rd" StorageClass="local-path"
```

**Comment by derekbit** [comment]
> While trying to use this provisioner to get rook-ceph to install, one of the PVCs that it tries to create wants to use `VolumeMode: Block`. Is this possible via this local-path-provisioner?
> 
> ```
> version: v0.0.30
> ```
> 
> ```
> "Failed to provision volume" err="rancher.io/local-path does not support block volume provisioning" 
> PVC="rook-ceph/set1-data-0pm7rd" StorageClass="local-path"
> ```

Currently, no.
