### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by tamalsaha** [rancher/local-path-provisioner#47]
We would like to see a release with https://github.com/rancher/local-path-provisioner/pull/46 pr. We are looking to use this with Kind in Github actions.
https://github.com/kubernetes-sigs/kind/issues/865 

Can you please cut a release?

Thanks.

**Comment by yasker** [comment]
Local Path Provisioner v0.0.10 has been [released].(https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.10)

**Comment by tamalsaha** [comment]
Thank you!
