### ISSUE TITLE
EACCES: permission denied, mkdir in local node path

### ISSUE THREAD

**Issue by kordeviant** [rancher/local-path-provisioner#5]
persisted volume on local node path /home/rancher/wp only creates directory wp but can not write to it.

**Comment by yasker** [comment]
Is it caused by security context like https://github.com/rancher/local-path-provisioner/issues/7 ?

**Comment by yasker** [comment]
Can you share the yaml file to reproduce it?

**Comment by kordeviant** [comment]
sorry it was fixed and needs nothing to be done. just had to chown root chmod 775 the directory.
