### ISSUE TITLE
Path Provisioner deletes volume from disk

### ISSUE THREAD

**Issue by phlegx** [rancher/local-path-provisioner#54]
After rebooting our development server it seems that the path provisioner **completely deleted the mongodb volume directory**.  We are using `Rancher 2.2.8` with `Kubernetes 1.14.6`

What can cause this? In our development server we use mongodb replica set helm chart but only one instance atm.

Here is the output from the `local-path-provisioner` which shows indeed that it got deleted

```[I] ➜ kubectl -n local-path-storage logs local-path-provisioner-f7986dc46-999vl 
time="2019-10-07T11:04:15Z" level=debug msg="Applied config: {\"nodePathMap\":[{\"node\":\"DEFAULT_PATH_FOR_NON_LISTED_NODES\",\"paths\":[\"/opt/local-path-provisioner\"]}]}" 
time="2019-10-07T11:04:15Z" level=debug msg="Provisioner started" 
time="2019-10-07T11:09:21Z" level=info msg="Deleting volume pvc-8316611a-de0f-11e9-856d-e23a50295529 at dev:/opt/local-path-provisioner/pvc-8316611a-de0f-11e9-856d-e23a50295529" 
time="2019-10-07T11:09:24Z" level=info msg="Volume pvc-8316611a-de0f-11e9-856d-e23a50295529 has been deleted on dev:/opt/local-path-provisioner/pvc-8316611a-de0f-11e9-856d-e23a50295529" ```

**Comment by yasker** [comment]
@phlegx As you can see [here](https://github.com/rancher/local-path-provisioner/blob/5b3969e1d01b8520b73d933e9aa18b6a2d38a633/provisioner.go#L245), the volume will only be deleted if:
1. The corresponding PV in Kubernetes has been deleted
2. And the reclaim policy is not set to `retain`

**Comment by yasker** [comment]
Yeah, Kubernetes document is also helpful.

I will close this issue for now.
