### ISSUE TITLE
Local path storage stuck in Pending state

### ISSUE THREAD

**Issue by BeneaAlinAndrei** [rancher/local-path-provisioner#61]
Hello,

After running `kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml` on my cluster i noticed that my pod will not leave **Pending State**. 

My cluster is created with Kubeadm verison 14.8, i am running the cluster on Ubuntu 18.04.3 LTS.

Please if someone knows how to pass this problem, and thank you!

https://github.com/rancher/local-path-provisioner#deployment

**Comment by yasker** [comment]
@BeneaAlinAndrei Have you tried the examples in the readme to see if it works?

You can check the reason of `pending` state of pod using `kubectl describe pod <podName>`. Also, the log of local path provisioner would be helpful.

**Comment by BeneaAlinAndrei** [comment]
> @BeneaAlinAndrei Have you tried the examples in the readme to see if it works?
> 
> You can check the reason of `pending` state of pod using `kubectl describe pod <podName>`. Also, the log of local path provisioner would be helpful.

I tried all the examples, they don't work, same as the pod, remain in Pending state.
The error is  Warning  FailedScheduling default-scheduler  0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.

**Comment by yasker** [comment]
@BeneaAlinAndrei According to the error message `Warning FailedScheduling default-scheduler 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.`, your pod didn't tolerate the taint on the node, so it failed to be scheduled. Since the pod cannot be scheduled, Kubernetes decided not to call the Local Path Provisioner to create the volume.

**Comment by BeneaAlinAndrei** [comment]
> @BeneaAlinAndrei According to the error message `Warning FailedScheduling default-scheduler 0/1 nodes are available: 1 node(s) had taints that the pod didn't tolerate.`, your pod didn't tolerate the taint on the node, so it failed to be scheduled. Since the pod cannot be scheduled, Kubernetes decided not to call the Local Path Provisioner to create the volume.

Thank you, that was the problem. I didn't unlock my master node in order to deploy on him. Thank you very much!
