### ISSUE TITLE
OpenShift 3.11

### ISSUE THREAD

**Issue by tamalsaha** [rancher/local-path-provisioner#69]
Has anyone got local-path-provisioner working with OpenShift 3.11 ? I am trying to get that working but so far unsuccessful. https://github.com/openshift/origin/issues/24377

**Comment by zhangguanzhang** [comment]
+1

**Comment by yasker** [comment]
We won't be able to support OpenShift 3.11 since it's using Kubernetes v1.11, which is below our version requirement (v1.12+).

**Comment by zhangguanzhang** [comment]
> We won't be able to support OpenShift 3.11 since it's using Kubernetes v1.11, which is below our version requirement (v1.12+).

same issue with the Openshift 4.5.9

**Comment by yasker** [comment]
@zhangguanzhang You meant: https://github.com/openshift/origin/issues/24377 ?

**Comment by zhangguanzhang** [comment]
Now I use other csi, if I meet again next time I will bring the log
