### ISSUE TITLE
Why the provisioner only support ReadWriteOnce

### ISSUE THREAD

**Issue by philpep** [rancher/local-path-provisioner#70]
Why the provisioner only support ReadWriteOnce pvc and not ReadOnlyMany/ReadWriteMany.

Since it's just a node-local directory, there's no problem with having multiple writer/readers as long as the application support this.

**Comment by yasker** [comment]
I am not sure I get what do you mean...

PV can only be used by the local node, and that's one node.

**Comment by philpep** [comment]
Hmm, I think I misunderstood goals of this project...
I thought that volumes where bound to a node and thus pods using the volume are automatically bound (via nodeAffinity) to the same node, and in this case ReadWriteMany is possible.

**Comment by yasker** [comment]
@philpep Yeah, the pod would be scheduled to the volume. But from the volume's perspective, it's still only capable of single node read/write. The pods on the other nodes cannot read/write the volume, so the volume is still RWO.

Though if you have multiple pods on the same node, they can read/write the volume at the same time. RWO is only about the node, not pods.

**Comment by philpep** [comment]
Ok thanks for the explanations @yasker !

**Comment by lsoica** [comment]
@yasker I also hit this limitation. My use case is that I am buiding a platform that could be installed both as single node k8s and multi node. For single node I am using a local storage provisioned, for multi node I'm leveraging rook. Now, I would like that for the apps deployed on top, the underlying storage provider to be transparent.

Some of the apps would need a storage class for shared volumes. I would like to use the same SC name, but in single node to be served by local provisioner, in multinode to be served by rook ceph. But the shared volumes requires RWX. So I cannot use this provisioner for local volumes.

Is there a real need for this restriction ?

**Comment by 0xMH** [comment]
I hit this exact limitation just lately when I was testing ReadWriteMany on kind. I know that being on single node RWX isn't need but does it causes any side effects hence its a restriction?

**Comment by acim** [comment]
Yes, it would be nice to have this possibility. I am running single node anyway and want to do volume backups using CronJob resource, I don't want to run backup on the host itself.

**Comment by dchirikov** [comment]
The path can be mounted on every node via NFS/Luster/GPFS/BeeGFS or other distributed FS, so I think this limitation should be tunable. Make it sense to make this behavior configurable?

**Comment by hwk42** [comment]
I have this issue ,but in my case ,there is only one node in the k3s cluster.this is describe pvc that is pending :
` Warning  ProvisioningFailed    9m20s (x16 over 174m)   rancher.io/local-path_local-path-provisioner-5ff76fc89d-sxbqd_992329ba-8162-47f2-9b27-6b3f14b70e0b  failed to provision volume with StorageClass "local-path": Only support ReadWriteOnce access mode
  Normal   ExternalProvisioning  4m21s (x683 over 174m)  persistentvolume-controller                                                                         waiting for a volume to be created, either by external provisioner "rancher.io/local-path" or manually created by system administrator`
any workaround to solve this? Thanks.

**Comment by hwk42** [comment]
Is it possible to support RWX , for example, as an option? In my case,pv is created by app with RWX mode,which is required by multi node env

**Comment by travisghansen** [comment]
I have a local hostpath driver as part of my project here: https://github.com/democratic-csi/democratic-csi

It does allow rwx but implicitly pins the volume through topology should crazy scenarios come up (ie: it’s safe to use in multi-node clusters as well).
