### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by mschae** [rancher/local-path-provisioner#73]
See #14 

I am using k3s on a i5 and the local path provisioner (version v0.0.11) sits at 18% CPU:
![grafik](https://user-images.githubusercontent.com/473241/73830577-2f128280-4805-11ea-8139-eec5fd2c1ee2.png)

Steps to reproduce:
1. Install k3s on x86 Hardware
2. Use the local path provisioner

Interestingly enough I am also running k3s on a cloud server, not using the local-path-provisioner (but having it running) and it doesn't consume nearly as many resources there.

**Comment by mshade** [comment]
I'm seeing this as well, with v0.0.11. For me, cpu usage starts low if I delete the pod and let it recreate, then after a while I see it back up in my top consumers.

I've just updated the manifest to v0.0.12 and will see if the issue persists.
