### ISSUE TITLE
docker URL when in corp set up

### ISSUE THREAD

**Issue by nijov** [rancher/local-path-provisioner#74]
How to configure docker registry URL to a private docker registry? Provisioner look for a busybox image from dockerhub to create the folders? How to set up provisioner in air gaped env?

**Comment by yasker** [comment]
You can refer to https://github.com/rancher/local-path-provisioner/issues/22#issuecomment-490984554 to setup custom image for the busybox image.

**Comment by priyavj08** [comment]
hi @yasker 
Can I give an alpine image instead busybox for helper image?  I can't use busybox image due to licensing issue

thanks and appreciate your reply on this
