### ISSUE TITLE
multiple local-path-provisioner for different host volumes

### ISSUE THREAD

**Issue by skwee** [rancher/local-path-provisioner#80]
**Question:** 
A single local-path-provisioner is working fine for me.
I have two different host volumes on my nodes (fast local ssd on /mnt/sdd, slow glusterfs on /mnt/gvol)
Might it be possible to setup two seperate storage classes with its own local-path-provisioner or is this out of scope ?

**Comment by skwee** [comment]
works by adding additional deployment and storage class. Sorry for the noise.

**Comment by deveshk0** [comment]
@skwee  can you explain the steps.

**Comment by WhiteBahamut** [comment]
would love to know that as well. creating a new depoyment and new storage class does not work for me :-/
