### ISSUE TITLE
add scripts to make it configurable for users when add/removing a dir 

### ISSUE THREAD

**Issue by nicktming** [rancher/local-path-provisioner#95]
when provisioning a pv, some users might want to add some operations besides (mkdir -p or rm -f), but now it is hardcoded in local-path-provisioner project.

i made some changes to make it configurable for users, i put it in ConfigMap(https://github.com/nicktming/local-path-provisioner/tree/dev-scripts/deploy/cm) when adding or removing a dir, the helper pod read add.sh and del.sh to config cmdsForPath in provisioner.go

if it is helpful, i would like to commit a pr for this feature.

**Comment by yasker** [comment]
@nicktming I like that idea. Yes, we can make them configurable.

There might be more we can do, e.g. set a quota for btrfs if needed if we implement certain parameter replacement. But that would be for later.

**Comment by nicktming** [comment]
@yasker i commit a pr at #99 which makes it configurable for users.

As for quota, i think users may have different requirements, for example users could use xqs_quota command at scripts if they use xfs. but it would be great if this project could set a quota regardless of file systems. I am also working on it and  i prefer to use xqs_quota command in configurable scripts now.
