### ISSUE TITLE
how to set nodePathMap

### ISSUE THREAD

**Issue by vivianforzj** [rancher/local-path-provisioner#98]
I tried:
```
helm install local-path-storage ./deploy/chart --set nodePathMap="[{node:DEFAULT_PATH_FOR_NON_LISTED_NODES,paths:[/data]}]" 
```

and got the error: 
```
Error: failed parsing --set data: error parsing index: strconv.Atoi: parsing "/data": invalid syntax
```

So, how can I set nodePathMap? Thanks for any help

**Comment by frederiko** [comment]
It's kind of annoying escaping json to be accepted with Helm --set. You will make yourself a favor by copying the `values.yaml` file, make the modification where you need and `helm install ... -f yourvalues.yaml`

**Comment by grapemix** [comment]
How about `helm install local-path-storage ./deploy/chart --set nodePathMap[0].node=DEFAULT_PATH_FOR_NON_LISTED_NODES --set nodePathMap[0].paths[0]=/data`?
